/* Generated by Yosys 0.53+39 (git sha1 388955031, g++ 12.2.0-14 -fPIC -O3) */

module BitwisePG(A, B, P, G);
  input A;
  wire A;
  input B;
  wire B;
  output G;
  wire G;
  output P;
  wire P;
  AND2x2_ASAP7_75t_R \G\AND2x2_ASAP7_75t_R  (
    .A(B),
    .B(A),
    .Y(G)
  );
  XOR2xp5_ASAP7_75t_R \P\XOR2xp5_ASAP7_75t_R  (
    .A(B),
    .B(A),
    .Y(P)
  );
endmodule

module BlackCell(Pi, Gi, Cin, Pj, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  input Pj;
  wire Pj;
  AO21x1_ASAP7_75t_R \G\AO21x1_ASAP7_75t_R  (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  AND2x2_ASAP7_75t_R \P\AND2x2_ASAP7_75t_R  (
    .A(Pi),
    .B(Pj),
    .Y(P)
  );
endmodule

module GrayCell(Pi, Gi, Cin, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  AO21x1_ASAP7_75t_R \G\AO21x1_ASAP7_75t_R  (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  assign P = Pi;
endmodule

module XorGate(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  XOR2xp5_ASAP7_75t_R \Y\XOR2xp5_ASAP7_75t_R  (
    .A(B),
    .B(A),
    .Y(Y)
  );
endmodule

module customAdder4_3(A, B, Sum);
  wire _0_;
  input [3:0] A;
  wire [3:0] A;
  input B;
  wire B;
  output [4:0] Sum;
  wire [4:0] Sum;
  TIELOx1_ASAP7_75t_R _1_ (
    .L(_0_)
  );
  unsignedBrentKungAdder4bit adder_module (
    .A(A),
    .B({ _0_, _0_, _0_, B }),
    .Sum(Sum)
  );
endmodule

module unsignedBrentKungAdder4bit(A, B, Sum);
  input [3:0] A;
  wire [3:0] A;
  input [3:0] B;
  wire [3:0] B;
  wire G_0_0;
  wire G_0_1;
  wire G_0_2;
  wire G_0_3;
  wire G_1_1;
  wire G_1_3;
  wire G_2_3;
  wire G_3_2;
  wire P_0_0;
  wire P_0_1;
  wire P_0_2;
  wire P_0_3;
  wire P_1_1;
  wire P_1_3;
  wire P_2_3;
  wire P_3_2;
  output [4:0] Sum;
  wire [4:0] Sum;
  BitwisePG uut0 (
    .A(A[0]),
    .B(B[0]),
    .G(G_0_0),
    .P(P_0_0)
  );
  BitwisePG uut1 (
    .A(A[1]),
    .B(B[1]),
    .G(G_0_1),
    .P(P_0_1)
  );
  XorGate uut10 (
    .A(P_0_3),
    .B(G_3_2),
    .Y(Sum[3])
  );
  BitwisePG uut2 (
    .A(A[2]),
    .B(B[2]),
    .G(G_0_2),
    .P(P_0_2)
  );
  BitwisePG uut3 (
    .A(A[3]),
    .B(B[3]),
    .G(G_0_3),
    .P(P_0_3)
  );
  GrayCell uut4 (
    .Cin(G_0_0),
    .G(G_1_1),
    .Gi(G_0_1),
    .P(P_1_1),
    .Pi(P_0_1)
  );
  BlackCell uut5 (
    .Cin(G_0_2),
    .G(G_1_3),
    .Gi(G_0_3),
    .P(P_1_3),
    .Pi(P_0_3),
    .Pj(P_0_2)
  );
  GrayCell uut6 (
    .Cin(G_1_1),
    .G(G_2_3),
    .Gi(G_1_3),
    .P(P_2_3),
    .Pi(P_1_3)
  );
  GrayCell uut7 (
    .Cin(G_1_1),
    .G(G_3_2),
    .Gi(G_0_2),
    .P(P_3_2),
    .Pi(P_0_2)
  );
  XorGate uut8 (
    .A(P_0_1),
    .B(G_0_0),
    .Y(Sum[1])
  );
  XorGate uut9 (
    .A(P_0_2),
    .B(G_1_1),
    .Y(Sum[2])
  );
  assign { Sum[4], Sum[0] } = { G_2_3, P_0_0 };
endmodule
