/* Generated by Yosys 0.53+39 (git sha1 388955031, g++ 12.2.0-14 -fPIC -O3) */

module NR_12_1(A, B, Product);
  input [11:0] A;
  wire [11:0] A;
  input B;
  wire B;
  output [11:0] Product;
  wire [11:0] Product;
  AND2x2_ASAP7_75t_R _00_ (
    .A(B),
    .B(A[0]),
    .Y(Product[0])
  );
  AND2x2_ASAP7_75t_R _01_ (
    .A(B),
    .B(A[10]),
    .Y(Product[10])
  );
  AND2x2_ASAP7_75t_R _02_ (
    .A(B),
    .B(A[11]),
    .Y(Product[11])
  );
  AND2x2_ASAP7_75t_R _03_ (
    .A(B),
    .B(A[1]),
    .Y(Product[1])
  );
  AND2x2_ASAP7_75t_R _04_ (
    .A(B),
    .B(A[2]),
    .Y(Product[2])
  );
  AND2x2_ASAP7_75t_R _05_ (
    .A(B),
    .B(A[3]),
    .Y(Product[3])
  );
  AND2x2_ASAP7_75t_R _06_ (
    .A(B),
    .B(A[4]),
    .Y(Product[4])
  );
  AND2x2_ASAP7_75t_R _07_ (
    .A(B),
    .B(A[5]),
    .Y(Product[5])
  );
  AND2x2_ASAP7_75t_R _08_ (
    .A(B),
    .B(A[6]),
    .Y(Product[6])
  );
  AND2x2_ASAP7_75t_R _09_ (
    .A(B),
    .B(A[7]),
    .Y(Product[7])
  );
  AND2x2_ASAP7_75t_R _10_ (
    .A(B),
    .B(A[8]),
    .Y(Product[8])
  );
  AND2x2_ASAP7_75t_R _11_ (
    .A(B),
    .B(A[9]),
    .Y(Product[9])
  );
endmodule
