/* Generated by Yosys 0.53+39 (git sha1 388955031, g++ 12.2.0-14 -fPIC -O3) */

module AndGate(a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  AND2x2_ASAP7_75t_R _0_ (
    .A(b),
    .B(a),
    .Y(y)
  );
endmodule

module NR_2_2(A, B, Product);
  input [1:0] A;
  wire [1:0] A;
  input [1:0] B;
  wire [1:0] B;
  wire P_0_0;
  wire P_0_1;
  wire P_1_0;
  wire P_1_1;
  output [3:0] Product;
  wire [3:0] Product;
  AndGate uut0 (
    .a(A[0]),
    .b(B[0]),
    .y(P_0_0)
  );
  AndGate uut1 (
    .a(A[1]),
    .b(B[0]),
    .y(P_0_1)
  );
  AndGate uut2 (
    .a(A[0]),
    .b(B[1]),
    .y(P_1_0)
  );
  AndGate uut3 (
    .a(A[1]),
    .b(B[1]),
    .y(P_1_1)
  );
  unsignedBrentKungAdder1bit uut4 (
    .A(P_0_1),
    .B(P_1_0),
    .Sum({ Product[3], Product[1] })
  );
  assign { Product[2], Product[0] } = { P_1_1, P_0_0 };
endmodule

module unsignedBrentKungAdder1bit(A, B, Sum);
  input A;
  wire A;
  input B;
  wire B;
  output [1:0] Sum;
  wire [1:0] Sum;
  AND2x2_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(Sum[1])
  );
  XOR2xp5_ASAP7_75t_R _1_ (
    .A(B),
    .B(A),
    .Y(Sum[0])
  );
endmodule
