/* Generated by Yosys 0.53+39 (git sha1 388955031, g++ 12.2.0-14 -fPIC -O3) */

module AndGate(a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  AND2x2_ASAP7_75t_R _0_ (
    .A(b),
    .B(a),
    .Y(y)
  );
endmodule

module BitwisePG(A, B, P, G);
  input A;
  wire A;
  input B;
  wire B;
  output G;
  wire G;
  output P;
  wire P;
  AND2x2_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(G)
  );
  XOR2xp5_ASAP7_75t_R _1_ (
    .A(B),
    .B(A),
    .Y(P)
  );
endmodule

module BlackCell(Pi, Gi, Cin, Pj, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  input Pj;
  wire Pj;
  AO21x1_ASAP7_75t_R _0_ (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  AND2x2_ASAP7_75t_R _1_ (
    .A(Pi),
    .B(Pj),
    .Y(P)
  );
endmodule

module GrayCell(Pi, Gi, Cin, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  AO21x1_ASAP7_75t_R _0_ (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  assign P = Pi;
endmodule

module NR_2_16(A, B, Product);
  input [1:0] A;
  wire [1:0] A;
  input [15:0] B;
  wire [15:0] B;
  wire P_0_0;
  wire P_0_1;
  wire P_10_0;
  wire P_10_1;
  wire P_11_0;
  wire P_11_1;
  wire P_12_0;
  wire P_12_1;
  wire P_13_0;
  wire P_13_1;
  wire P_14_0;
  wire P_14_1;
  wire P_15_0;
  wire P_15_1;
  wire P_1_0;
  wire P_1_1;
  wire P_2_0;
  wire P_2_1;
  wire P_3_0;
  wire P_3_1;
  wire P_4_0;
  wire P_4_1;
  wire P_5_0;
  wire P_5_1;
  wire P_6_0;
  wire P_6_1;
  wire P_7_0;
  wire P_7_1;
  wire P_8_0;
  wire P_8_1;
  wire P_9_0;
  wire P_9_1;
  output [17:0] Product;
  wire [17:0] Product;
  AndGate uut0 (
    .a(A[0]),
    .b(B[0]),
    .y(P_0_0)
  );
  AndGate uut1 (
    .a(A[1]),
    .b(B[0]),
    .y(P_0_1)
  );
  AndGate uut10 (
    .a(A[0]),
    .b(B[5]),
    .y(P_5_0)
  );
  AndGate uut11 (
    .a(A[1]),
    .b(B[5]),
    .y(P_5_1)
  );
  AndGate uut12 (
    .a(A[0]),
    .b(B[6]),
    .y(P_6_0)
  );
  AndGate uut13 (
    .a(A[1]),
    .b(B[6]),
    .y(P_6_1)
  );
  AndGate uut14 (
    .a(A[0]),
    .b(B[7]),
    .y(P_7_0)
  );
  AndGate uut15 (
    .a(A[1]),
    .b(B[7]),
    .y(P_7_1)
  );
  AndGate uut16 (
    .a(A[0]),
    .b(B[8]),
    .y(P_8_0)
  );
  AndGate uut17 (
    .a(A[1]),
    .b(B[8]),
    .y(P_8_1)
  );
  AndGate uut18 (
    .a(A[0]),
    .b(B[9]),
    .y(P_9_0)
  );
  AndGate uut19 (
    .a(A[1]),
    .b(B[9]),
    .y(P_9_1)
  );
  AndGate uut2 (
    .a(A[0]),
    .b(B[1]),
    .y(P_1_0)
  );
  AndGate uut20 (
    .a(A[0]),
    .b(B[10]),
    .y(P_10_0)
  );
  AndGate uut21 (
    .a(A[1]),
    .b(B[10]),
    .y(P_10_1)
  );
  AndGate uut22 (
    .a(A[0]),
    .b(B[11]),
    .y(P_11_0)
  );
  AndGate uut23 (
    .a(A[1]),
    .b(B[11]),
    .y(P_11_1)
  );
  AndGate uut24 (
    .a(A[0]),
    .b(B[12]),
    .y(P_12_0)
  );
  AndGate uut25 (
    .a(A[1]),
    .b(B[12]),
    .y(P_12_1)
  );
  AndGate uut26 (
    .a(A[0]),
    .b(B[13]),
    .y(P_13_0)
  );
  AndGate uut27 (
    .a(A[1]),
    .b(B[13]),
    .y(P_13_1)
  );
  AndGate uut28 (
    .a(A[0]),
    .b(B[14]),
    .y(P_14_0)
  );
  AndGate uut29 (
    .a(A[1]),
    .b(B[14]),
    .y(P_14_1)
  );
  AndGate uut3 (
    .a(A[1]),
    .b(B[1]),
    .y(P_1_1)
  );
  AndGate uut30 (
    .a(A[0]),
    .b(B[15]),
    .y(P_15_0)
  );
  AndGate uut31 (
    .a(A[1]),
    .b(B[15]),
    .y(P_15_1)
  );
  unsignedBrentKungAdder15bit uut32 (
    .A({ P_14_1, P_13_1, P_12_1, P_11_1, P_10_1, P_9_1, P_8_1, P_7_1, P_6_1, P_5_1, P_4_1, P_3_1, P_2_1, P_1_1, P_0_1 }),
    .B({ P_15_0, P_14_0, P_13_0, P_12_0, P_11_0, P_10_0, P_9_0, P_8_0, P_7_0, P_6_0, P_5_0, P_4_0, P_3_0, P_2_0, P_1_0 }),
    .Sum({ Product[17], Product[15:1] })
  );
  AndGate uut4 (
    .a(A[0]),
    .b(B[2]),
    .y(P_2_0)
  );
  AndGate uut5 (
    .a(A[1]),
    .b(B[2]),
    .y(P_2_1)
  );
  AndGate uut6 (
    .a(A[0]),
    .b(B[3]),
    .y(P_3_0)
  );
  AndGate uut7 (
    .a(A[1]),
    .b(B[3]),
    .y(P_3_1)
  );
  AndGate uut8 (
    .a(A[0]),
    .b(B[4]),
    .y(P_4_0)
  );
  AndGate uut9 (
    .a(A[1]),
    .b(B[4]),
    .y(P_4_1)
  );
  assign { Product[16], Product[0] } = { P_15_1, P_0_0 };
endmodule

module XorGate(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  XOR2xp5_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(Y)
  );
endmodule

module unsignedBrentKungAdder15bit(A, B, Sum);
  input [14:0] A;
  wire [14:0] A;
  input [14:0] B;
  wire [14:0] B;
  wire G_0_0;
  wire G_0_1;
  wire G_0_10;
  wire G_0_11;
  wire G_0_12;
  wire G_0_13;
  wire G_0_14;
  wire G_0_2;
  wire G_0_3;
  wire G_0_4;
  wire G_0_5;
  wire G_0_6;
  wire G_0_7;
  wire G_0_8;
  wire G_0_9;
  wire G_1_1;
  wire G_1_11;
  wire G_1_13;
  wire G_1_3;
  wire G_1_5;
  wire G_1_7;
  wire G_1_9;
  wire G_2_11;
  wire G_2_3;
  wire G_2_7;
  wire G_3_7;
  wire G_5_11;
  wire G_6_13;
  wire G_6_5;
  wire G_6_9;
  wire G_7_10;
  wire G_7_12;
  wire G_7_14;
  wire G_7_2;
  wire G_7_4;
  wire G_7_6;
  wire G_7_8;
  wire P_0_0;
  wire P_0_1;
  wire P_0_10;
  wire P_0_11;
  wire P_0_12;
  wire P_0_13;
  wire P_0_14;
  wire P_0_2;
  wire P_0_3;
  wire P_0_4;
  wire P_0_5;
  wire P_0_6;
  wire P_0_7;
  wire P_0_8;
  wire P_0_9;
  wire P_1_1;
  wire P_1_11;
  wire P_1_13;
  wire P_1_3;
  wire P_1_5;
  wire P_1_7;
  wire P_1_9;
  wire P_2_11;
  wire P_2_3;
  wire P_2_7;
  wire P_3_7;
  wire P_5_11;
  wire P_6_13;
  wire P_6_5;
  wire P_6_9;
  wire P_7_10;
  wire P_7_12;
  wire P_7_14;
  wire P_7_2;
  wire P_7_4;
  wire P_7_6;
  wire P_7_8;
  output [15:0] Sum;
  wire [15:0] Sum;
  BitwisePG uut0 (
    .A(A[0]),
    .B(B[0]),
    .G(G_0_0),
    .P(P_0_0)
  );
  BitwisePG uut1 (
    .A(A[1]),
    .B(B[1]),
    .G(G_0_1),
    .P(P_0_1)
  );
  BitwisePG uut10 (
    .A(A[10]),
    .B(B[10]),
    .G(G_0_10),
    .P(P_0_10)
  );
  BitwisePG uut11 (
    .A(A[11]),
    .B(B[11]),
    .G(G_0_11),
    .P(P_0_11)
  );
  BitwisePG uut12 (
    .A(A[12]),
    .B(B[12]),
    .G(G_0_12),
    .P(P_0_12)
  );
  BitwisePG uut13 (
    .A(A[13]),
    .B(B[13]),
    .G(G_0_13),
    .P(P_0_13)
  );
  BitwisePG uut14 (
    .A(A[14]),
    .B(B[14]),
    .G(G_0_14),
    .P(P_0_14)
  );
  GrayCell uut15 (
    .Cin(G_0_0),
    .G(G_1_1),
    .Gi(G_0_1),
    .P(P_1_1),
    .Pi(P_0_1)
  );
  BlackCell uut16 (
    .Cin(G_0_2),
    .G(G_1_3),
    .Gi(G_0_3),
    .P(P_1_3),
    .Pi(P_0_3),
    .Pj(P_0_2)
  );
  BlackCell uut17 (
    .Cin(G_0_4),
    .G(G_1_5),
    .Gi(G_0_5),
    .P(P_1_5),
    .Pi(P_0_5),
    .Pj(P_0_4)
  );
  BlackCell uut18 (
    .Cin(G_0_6),
    .G(G_1_7),
    .Gi(G_0_7),
    .P(P_1_7),
    .Pi(P_0_7),
    .Pj(P_0_6)
  );
  BlackCell uut19 (
    .Cin(G_0_8),
    .G(G_1_9),
    .Gi(G_0_9),
    .P(P_1_9),
    .Pi(P_0_9),
    .Pj(P_0_8)
  );
  BitwisePG uut2 (
    .A(A[2]),
    .B(B[2]),
    .G(G_0_2),
    .P(P_0_2)
  );
  BlackCell uut20 (
    .Cin(G_0_10),
    .G(G_1_11),
    .Gi(G_0_11),
    .P(P_1_11),
    .Pi(P_0_11),
    .Pj(P_0_10)
  );
  BlackCell uut21 (
    .Cin(G_0_12),
    .G(G_1_13),
    .Gi(G_0_13),
    .P(P_1_13),
    .Pi(P_0_13),
    .Pj(P_0_12)
  );
  GrayCell uut22 (
    .Cin(G_1_1),
    .G(G_2_3),
    .Gi(G_1_3),
    .P(P_2_3),
    .Pi(P_1_3)
  );
  BlackCell uut23 (
    .Cin(G_1_5),
    .G(G_2_7),
    .Gi(G_1_7),
    .P(P_2_7),
    .Pi(P_1_7),
    .Pj(P_1_5)
  );
  BlackCell uut24 (
    .Cin(G_1_9),
    .G(G_2_11),
    .Gi(G_1_11),
    .P(P_2_11),
    .Pi(P_1_11),
    .Pj(P_1_9)
  );
  GrayCell uut25 (
    .Cin(G_2_3),
    .G(G_3_7),
    .Gi(G_2_7),
    .P(P_3_7),
    .Pi(P_2_7)
  );
  GrayCell uut26 (
    .Cin(G_3_7),
    .G(G_5_11),
    .Gi(G_2_11),
    .P(P_5_11),
    .Pi(P_2_11)
  );
  GrayCell uut27 (
    .Cin(G_2_3),
    .G(G_6_5),
    .Gi(G_1_5),
    .P(P_6_5),
    .Pi(P_1_5)
  );
  GrayCell uut28 (
    .Cin(G_3_7),
    .G(G_6_9),
    .Gi(G_1_9),
    .P(P_6_9),
    .Pi(P_1_9)
  );
  GrayCell uut29 (
    .Cin(G_5_11),
    .G(G_6_13),
    .Gi(G_1_13),
    .P(P_6_13),
    .Pi(P_1_13)
  );
  BitwisePG uut3 (
    .A(A[3]),
    .B(B[3]),
    .G(G_0_3),
    .P(P_0_3)
  );
  GrayCell uut30 (
    .Cin(G_1_1),
    .G(G_7_2),
    .Gi(G_0_2),
    .P(P_7_2),
    .Pi(P_0_2)
  );
  GrayCell uut31 (
    .Cin(G_2_3),
    .G(G_7_4),
    .Gi(G_0_4),
    .P(P_7_4),
    .Pi(P_0_4)
  );
  GrayCell uut32 (
    .Cin(G_6_5),
    .G(G_7_6),
    .Gi(G_0_6),
    .P(P_7_6),
    .Pi(P_0_6)
  );
  GrayCell uut33 (
    .Cin(G_3_7),
    .G(G_7_8),
    .Gi(G_0_8),
    .P(P_7_8),
    .Pi(P_0_8)
  );
  GrayCell uut34 (
    .Cin(G_6_9),
    .G(G_7_10),
    .Gi(G_0_10),
    .P(P_7_10),
    .Pi(P_0_10)
  );
  GrayCell uut35 (
    .Cin(G_5_11),
    .G(G_7_12),
    .Gi(G_0_12),
    .P(P_7_12),
    .Pi(P_0_12)
  );
  GrayCell uut36 (
    .Cin(G_6_13),
    .G(G_7_14),
    .Gi(G_0_14),
    .P(P_7_14),
    .Pi(P_0_14)
  );
  XorGate uut37 (
    .A(P_0_1),
    .B(G_0_0),
    .Y(Sum[1])
  );
  XorGate uut38 (
    .A(P_0_2),
    .B(G_1_1),
    .Y(Sum[2])
  );
  XorGate uut39 (
    .A(P_0_3),
    .B(G_7_2),
    .Y(Sum[3])
  );
  BitwisePG uut4 (
    .A(A[4]),
    .B(B[4]),
    .G(G_0_4),
    .P(P_0_4)
  );
  XorGate uut40 (
    .A(P_0_4),
    .B(G_2_3),
    .Y(Sum[4])
  );
  XorGate uut41 (
    .A(P_0_5),
    .B(G_7_4),
    .Y(Sum[5])
  );
  XorGate uut42 (
    .A(P_0_6),
    .B(G_6_5),
    .Y(Sum[6])
  );
  XorGate uut43 (
    .A(P_0_7),
    .B(G_7_6),
    .Y(Sum[7])
  );
  XorGate uut44 (
    .A(P_0_8),
    .B(G_3_7),
    .Y(Sum[8])
  );
  XorGate uut45 (
    .A(P_0_9),
    .B(G_7_8),
    .Y(Sum[9])
  );
  XorGate uut46 (
    .A(P_0_10),
    .B(G_6_9),
    .Y(Sum[10])
  );
  XorGate uut47 (
    .A(P_0_11),
    .B(G_7_10),
    .Y(Sum[11])
  );
  XorGate uut48 (
    .A(P_0_12),
    .B(G_5_11),
    .Y(Sum[12])
  );
  XorGate uut49 (
    .A(P_0_13),
    .B(G_7_12),
    .Y(Sum[13])
  );
  BitwisePG uut5 (
    .A(A[5]),
    .B(B[5]),
    .G(G_0_5),
    .P(P_0_5)
  );
  XorGate uut50 (
    .A(P_0_14),
    .B(G_6_13),
    .Y(Sum[14])
  );
  BitwisePG uut6 (
    .A(A[6]),
    .B(B[6]),
    .G(G_0_6),
    .P(P_0_6)
  );
  BitwisePG uut7 (
    .A(A[7]),
    .B(B[7]),
    .G(G_0_7),
    .P(P_0_7)
  );
  BitwisePG uut8 (
    .A(A[8]),
    .B(B[8]),
    .G(G_0_8),
    .P(P_0_8)
  );
  BitwisePG uut9 (
    .A(A[9]),
    .B(B[9]),
    .G(G_0_9),
    .P(P_0_9)
  );
  assign { Sum[15], Sum[0] } = { G_7_14, P_0_0 };
endmodule
