/* Generated by Yosys 0.53+39 (git sha1 388955031, g++ 12.2.0-14 -fPIC -O3) */

module AndGate(a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  AND2x2_ASAP7_75t_R _0_ (
    .A(b),
    .B(a),
    .Y(y)
  );
endmodule

module BitwisePG(A, B, P, G);
  input A;
  wire A;
  input B;
  wire B;
  output G;
  wire G;
  output P;
  wire P;
  AND2x2_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(G)
  );
  XOR2xp5_ASAP7_75t_R _1_ (
    .A(B),
    .B(A),
    .Y(P)
  );
endmodule

module BlackCell(Pi, Gi, Cin, Pj, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  input Pj;
  wire Pj;
  AO21x1_ASAP7_75t_R _0_ (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  AND2x2_ASAP7_75t_R _1_ (
    .A(Pi),
    .B(Pj),
    .Y(P)
  );
endmodule

module FullAdder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output sum;
  wire sum;
  MAJx2_ASAP7_75t_R _2_ (
    .A(b),
    .B(a),
    .C(cin),
    .Y(cout)
  );
  NOR3xp33_ASAP7_75t_R _3_ (
    .A(b),
    .B(a),
    .C(cin),
    .Y(_0_)
  );
  NAND3xp33_ASAP7_75t_R _4_ (
    .A(b),
    .B(a),
    .C(cin),
    .Y(_1_)
  );
  OAI21xp33_ASAP7_75t_R _5_ (
    .A1(cout),
    .A2(_0_),
    .B(_1_),
    .Y(sum)
  );
endmodule

module GrayCell(Pi, Gi, Cin, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  AO21x1_ASAP7_75t_R _0_ (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  assign P = Pi;
endmodule

module HalfAdder(a, b, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  output cout;
  wire cout;
  output sum;
  wire sum;
  AND2x2_ASAP7_75t_R _0_ (
    .A(b),
    .B(a),
    .Y(cout)
  );
  XOR2xp5_ASAP7_75t_R _1_ (
    .A(b),
    .B(a),
    .Y(sum)
  );
endmodule

module NR_5_28(A, B, Product);
  input [4:0] A;
  wire [4:0] A;
  input [27:0] B;
  wire [27:0] B;
  wire P_0_0;
  wire P_0_1;
  wire P_0_2;
  wire P_0_3;
  wire P_0_4;
  wire P_10_0;
  wire P_10_1;
  wire P_10_2;
  wire P_10_3;
  wire P_10_4;
  wire P_11_0;
  wire P_11_1;
  wire P_11_2;
  wire P_11_3;
  wire P_11_4;
  wire P_12_0;
  wire P_12_1;
  wire P_12_2;
  wire P_12_3;
  wire P_12_4;
  wire P_13_0;
  wire P_13_1;
  wire P_13_2;
  wire P_13_3;
  wire P_13_4;
  wire P_14_0;
  wire P_14_1;
  wire P_14_2;
  wire P_14_3;
  wire P_14_4;
  wire P_15_0;
  wire P_15_1;
  wire P_15_2;
  wire P_15_3;
  wire P_15_4;
  wire P_16_0;
  wire P_16_1;
  wire P_16_2;
  wire P_16_3;
  wire P_16_4;
  wire P_17_0;
  wire P_17_1;
  wire P_17_2;
  wire P_17_3;
  wire P_17_4;
  wire P_18_0;
  wire P_18_1;
  wire P_18_2;
  wire P_18_3;
  wire P_18_4;
  wire P_19_0;
  wire P_19_1;
  wire P_19_2;
  wire P_19_3;
  wire P_19_4;
  wire P_1_0;
  wire P_1_1;
  wire P_1_2;
  wire P_1_3;
  wire P_1_4;
  wire P_20_0;
  wire P_20_1;
  wire P_20_2;
  wire P_20_3;
  wire P_20_4;
  wire P_21_0;
  wire P_21_1;
  wire P_21_2;
  wire P_21_3;
  wire P_21_4;
  wire P_22_0;
  wire P_22_1;
  wire P_22_2;
  wire P_22_3;
  wire P_22_4;
  wire P_23_0;
  wire P_23_1;
  wire P_23_2;
  wire P_23_3;
  wire P_23_4;
  wire P_24_0;
  wire P_24_1;
  wire P_24_2;
  wire P_24_3;
  wire P_24_4;
  wire P_25_0;
  wire P_25_1;
  wire P_25_2;
  wire P_25_3;
  wire P_25_4;
  wire P_26_0;
  wire P_26_1;
  wire P_26_2;
  wire P_26_3;
  wire P_26_4;
  wire P_27_0;
  wire P_27_1;
  wire P_27_2;
  wire P_27_3;
  wire P_27_4;
  wire P_2_0;
  wire P_2_1;
  wire P_2_2;
  wire P_2_3;
  wire P_2_4;
  wire P_3_0;
  wire P_3_1;
  wire P_3_2;
  wire P_3_3;
  wire P_3_4;
  wire P_4_0;
  wire P_4_1;
  wire P_4_2;
  wire P_4_3;
  wire P_4_4;
  wire P_5_0;
  wire P_5_1;
  wire P_5_2;
  wire P_5_3;
  wire P_5_4;
  wire P_6_0;
  wire P_6_1;
  wire P_6_2;
  wire P_6_3;
  wire P_6_4;
  wire P_7_0;
  wire P_7_1;
  wire P_7_2;
  wire P_7_3;
  wire P_7_4;
  wire P_8_0;
  wire P_8_1;
  wire P_8_2;
  wire P_8_3;
  wire P_8_4;
  wire P_9_0;
  wire P_9_1;
  wire P_9_2;
  wire P_9_3;
  wire P_9_4;
  output [32:0] Product;
  wire [32:0] Product;
  wire c0;
  wire c1;
  wire c10;
  wire c11;
  wire c12;
  wire c13;
  wire c14;
  wire c15;
  wire c16;
  wire c17;
  wire c18;
  wire c19;
  wire c2;
  wire c20;
  wire c21;
  wire c22;
  wire c23;
  wire c24;
  wire c25;
  wire c26;
  wire c27;
  wire c28;
  wire c29;
  wire c3;
  wire c30;
  wire c31;
  wire c32;
  wire c33;
  wire c34;
  wire c35;
  wire c36;
  wire c37;
  wire c38;
  wire c39;
  wire c4;
  wire c40;
  wire c41;
  wire c42;
  wire c43;
  wire c44;
  wire c45;
  wire c46;
  wire c47;
  wire c48;
  wire c49;
  wire c5;
  wire c50;
  wire c51;
  wire c52;
  wire c53;
  wire c54;
  wire c55;
  wire c56;
  wire c57;
  wire c58;
  wire c59;
  wire c6;
  wire c60;
  wire c61;
  wire c62;
  wire c63;
  wire c64;
  wire c65;
  wire c66;
  wire c67;
  wire c68;
  wire c69;
  wire c7;
  wire c70;
  wire c71;
  wire c72;
  wire c73;
  wire c74;
  wire c75;
  wire c76;
  wire c77;
  wire c78;
  wire c79;
  wire c8;
  wire c80;
  wire c9;
  wire s0;
  wire s1;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s2;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s3;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s4;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s45;
  wire s46;
  wire s47;
  wire s48;
  wire s49;
  wire s5;
  wire s50;
  wire s51;
  wire s52;
  wire s53;
  wire s54;
  wire s55;
  wire s56;
  wire s57;
  wire s58;
  wire s59;
  wire s6;
  wire s60;
  wire s61;
  wire s62;
  wire s63;
  wire s64;
  wire s65;
  wire s66;
  wire s67;
  wire s68;
  wire s69;
  wire s7;
  wire s70;
  wire s71;
  wire s72;
  wire s73;
  wire s74;
  wire s75;
  wire s76;
  wire s77;
  wire s78;
  wire s79;
  wire s8;
  wire s80;
  wire s9;
  AndGate uut0 (
    .a(A[0]),
    .b(B[0]),
    .y(P_0_0)
  );
  AndGate uut1 (
    .a(A[1]),
    .b(B[0]),
    .y(P_0_1)
  );
  AndGate uut10 (
    .a(A[0]),
    .b(B[2]),
    .y(P_2_0)
  );
  AndGate uut100 (
    .a(A[0]),
    .b(B[20]),
    .y(P_20_0)
  );
  AndGate uut101 (
    .a(A[1]),
    .b(B[20]),
    .y(P_20_1)
  );
  AndGate uut102 (
    .a(A[2]),
    .b(B[20]),
    .y(P_20_2)
  );
  AndGate uut103 (
    .a(A[3]),
    .b(B[20]),
    .y(P_20_3)
  );
  AndGate uut104 (
    .a(A[4]),
    .b(B[20]),
    .y(P_20_4)
  );
  AndGate uut105 (
    .a(A[0]),
    .b(B[21]),
    .y(P_21_0)
  );
  AndGate uut106 (
    .a(A[1]),
    .b(B[21]),
    .y(P_21_1)
  );
  AndGate uut107 (
    .a(A[2]),
    .b(B[21]),
    .y(P_21_2)
  );
  AndGate uut108 (
    .a(A[3]),
    .b(B[21]),
    .y(P_21_3)
  );
  AndGate uut109 (
    .a(A[4]),
    .b(B[21]),
    .y(P_21_4)
  );
  AndGate uut11 (
    .a(A[1]),
    .b(B[2]),
    .y(P_2_1)
  );
  AndGate uut110 (
    .a(A[0]),
    .b(B[22]),
    .y(P_22_0)
  );
  AndGate uut111 (
    .a(A[1]),
    .b(B[22]),
    .y(P_22_1)
  );
  AndGate uut112 (
    .a(A[2]),
    .b(B[22]),
    .y(P_22_2)
  );
  AndGate uut113 (
    .a(A[3]),
    .b(B[22]),
    .y(P_22_3)
  );
  AndGate uut114 (
    .a(A[4]),
    .b(B[22]),
    .y(P_22_4)
  );
  AndGate uut115 (
    .a(A[0]),
    .b(B[23]),
    .y(P_23_0)
  );
  AndGate uut116 (
    .a(A[1]),
    .b(B[23]),
    .y(P_23_1)
  );
  AndGate uut117 (
    .a(A[2]),
    .b(B[23]),
    .y(P_23_2)
  );
  AndGate uut118 (
    .a(A[3]),
    .b(B[23]),
    .y(P_23_3)
  );
  AndGate uut119 (
    .a(A[4]),
    .b(B[23]),
    .y(P_23_4)
  );
  AndGate uut12 (
    .a(A[2]),
    .b(B[2]),
    .y(P_2_2)
  );
  AndGate uut120 (
    .a(A[0]),
    .b(B[24]),
    .y(P_24_0)
  );
  AndGate uut121 (
    .a(A[1]),
    .b(B[24]),
    .y(P_24_1)
  );
  AndGate uut122 (
    .a(A[2]),
    .b(B[24]),
    .y(P_24_2)
  );
  AndGate uut123 (
    .a(A[3]),
    .b(B[24]),
    .y(P_24_3)
  );
  AndGate uut124 (
    .a(A[4]),
    .b(B[24]),
    .y(P_24_4)
  );
  AndGate uut125 (
    .a(A[0]),
    .b(B[25]),
    .y(P_25_0)
  );
  AndGate uut126 (
    .a(A[1]),
    .b(B[25]),
    .y(P_25_1)
  );
  AndGate uut127 (
    .a(A[2]),
    .b(B[25]),
    .y(P_25_2)
  );
  AndGate uut128 (
    .a(A[3]),
    .b(B[25]),
    .y(P_25_3)
  );
  AndGate uut129 (
    .a(A[4]),
    .b(B[25]),
    .y(P_25_4)
  );
  AndGate uut13 (
    .a(A[3]),
    .b(B[2]),
    .y(P_2_3)
  );
  AndGate uut130 (
    .a(A[0]),
    .b(B[26]),
    .y(P_26_0)
  );
  AndGate uut131 (
    .a(A[1]),
    .b(B[26]),
    .y(P_26_1)
  );
  AndGate uut132 (
    .a(A[2]),
    .b(B[26]),
    .y(P_26_2)
  );
  AndGate uut133 (
    .a(A[3]),
    .b(B[26]),
    .y(P_26_3)
  );
  AndGate uut134 (
    .a(A[4]),
    .b(B[26]),
    .y(P_26_4)
  );
  AndGate uut135 (
    .a(A[0]),
    .b(B[27]),
    .y(P_27_0)
  );
  AndGate uut136 (
    .a(A[1]),
    .b(B[27]),
    .y(P_27_1)
  );
  AndGate uut137 (
    .a(A[2]),
    .b(B[27]),
    .y(P_27_2)
  );
  AndGate uut138 (
    .a(A[3]),
    .b(B[27]),
    .y(P_27_3)
  );
  AndGate uut139 (
    .a(A[4]),
    .b(B[27]),
    .y(P_27_4)
  );
  AndGate uut14 (
    .a(A[4]),
    .b(B[2]),
    .y(P_2_4)
  );
  HalfAdder uut140 (
    .a(P_0_4),
    .b(P_1_3),
    .cout(c0),
    .sum(s0)
  );
  FullAdder uut141 (
    .a(P_1_4),
    .b(P_2_3),
    .cin(P_3_2),
    .cout(c1),
    .sum(s1)
  );
  FullAdder uut142 (
    .a(P_2_4),
    .b(P_3_3),
    .cin(P_4_2),
    .cout(c2),
    .sum(s2)
  );
  FullAdder uut143 (
    .a(P_3_4),
    .b(P_4_3),
    .cin(P_5_2),
    .cout(c3),
    .sum(s3)
  );
  FullAdder uut144 (
    .a(P_4_4),
    .b(P_5_3),
    .cin(P_6_2),
    .cout(c4),
    .sum(s4)
  );
  FullAdder uut145 (
    .a(P_5_4),
    .b(P_6_3),
    .cin(P_7_2),
    .cout(c5),
    .sum(s5)
  );
  FullAdder uut146 (
    .a(P_6_4),
    .b(P_7_3),
    .cin(P_8_2),
    .cout(c6),
    .sum(s6)
  );
  FullAdder uut147 (
    .a(P_7_4),
    .b(P_8_3),
    .cin(P_9_2),
    .cout(c7),
    .sum(s7)
  );
  FullAdder uut148 (
    .a(P_8_4),
    .b(P_9_3),
    .cin(P_10_2),
    .cout(c8),
    .sum(s8)
  );
  FullAdder uut149 (
    .a(P_9_4),
    .b(P_10_3),
    .cin(P_11_2),
    .cout(c9),
    .sum(s9)
  );
  AndGate uut15 (
    .a(A[0]),
    .b(B[3]),
    .y(P_3_0)
  );
  FullAdder uut150 (
    .a(P_10_4),
    .b(P_11_3),
    .cin(P_12_2),
    .cout(c10),
    .sum(s10)
  );
  FullAdder uut151 (
    .a(P_11_4),
    .b(P_12_3),
    .cin(P_13_2),
    .cout(c11),
    .sum(s11)
  );
  FullAdder uut152 (
    .a(P_12_4),
    .b(P_13_3),
    .cin(P_14_2),
    .cout(c12),
    .sum(s12)
  );
  FullAdder uut153 (
    .a(P_13_4),
    .b(P_14_3),
    .cin(P_15_2),
    .cout(c13),
    .sum(s13)
  );
  FullAdder uut154 (
    .a(P_14_4),
    .b(P_15_3),
    .cin(P_16_2),
    .cout(c14),
    .sum(s14)
  );
  FullAdder uut155 (
    .a(P_15_4),
    .b(P_16_3),
    .cin(P_17_2),
    .cout(c15),
    .sum(s15)
  );
  FullAdder uut156 (
    .a(P_16_4),
    .b(P_17_3),
    .cin(P_18_2),
    .cout(c16),
    .sum(s16)
  );
  FullAdder uut157 (
    .a(P_17_4),
    .b(P_18_3),
    .cin(P_19_2),
    .cout(c17),
    .sum(s17)
  );
  FullAdder uut158 (
    .a(P_18_4),
    .b(P_19_3),
    .cin(P_20_2),
    .cout(c18),
    .sum(s18)
  );
  FullAdder uut159 (
    .a(P_19_4),
    .b(P_20_3),
    .cin(P_21_2),
    .cout(c19),
    .sum(s19)
  );
  AndGate uut16 (
    .a(A[1]),
    .b(B[3]),
    .y(P_3_1)
  );
  FullAdder uut160 (
    .a(P_20_4),
    .b(P_21_3),
    .cin(P_22_2),
    .cout(c20),
    .sum(s20)
  );
  FullAdder uut161 (
    .a(P_21_4),
    .b(P_22_3),
    .cin(P_23_2),
    .cout(c21),
    .sum(s21)
  );
  FullAdder uut162 (
    .a(P_22_4),
    .b(P_23_3),
    .cin(P_24_2),
    .cout(c22),
    .sum(s22)
  );
  FullAdder uut163 (
    .a(P_23_4),
    .b(P_24_3),
    .cin(P_25_2),
    .cout(c23),
    .sum(s23)
  );
  HalfAdder uut164 (
    .a(P_24_4),
    .b(P_25_3),
    .cout(c24),
    .sum(s24)
  );
  HalfAdder uut165 (
    .a(P_0_3),
    .b(P_1_2),
    .cout(c25),
    .sum(s25)
  );
  FullAdder uut166 (
    .a(P_2_2),
    .b(P_3_1),
    .cin(P_4_0),
    .cout(c26),
    .sum(s26)
  );
  FullAdder uut167 (
    .a(P_4_1),
    .b(P_5_0),
    .cin(c0),
    .cout(c27),
    .sum(s27)
  );
  FullAdder uut168 (
    .a(P_5_1),
    .b(P_6_0),
    .cin(c1),
    .cout(c28),
    .sum(s28)
  );
  FullAdder uut169 (
    .a(P_6_1),
    .b(P_7_0),
    .cin(c2),
    .cout(c29),
    .sum(s29)
  );
  AndGate uut17 (
    .a(A[2]),
    .b(B[3]),
    .y(P_3_2)
  );
  FullAdder uut170 (
    .a(P_7_1),
    .b(P_8_0),
    .cin(c3),
    .cout(c30),
    .sum(s30)
  );
  FullAdder uut171 (
    .a(P_8_1),
    .b(P_9_0),
    .cin(c4),
    .cout(c31),
    .sum(s31)
  );
  FullAdder uut172 (
    .a(P_9_1),
    .b(P_10_0),
    .cin(c5),
    .cout(c32),
    .sum(s32)
  );
  FullAdder uut173 (
    .a(P_10_1),
    .b(P_11_0),
    .cin(c6),
    .cout(c33),
    .sum(s33)
  );
  FullAdder uut174 (
    .a(P_11_1),
    .b(P_12_0),
    .cin(c7),
    .cout(c34),
    .sum(s34)
  );
  FullAdder uut175 (
    .a(P_12_1),
    .b(P_13_0),
    .cin(c8),
    .cout(c35),
    .sum(s35)
  );
  FullAdder uut176 (
    .a(P_13_1),
    .b(P_14_0),
    .cin(c9),
    .cout(c36),
    .sum(s36)
  );
  FullAdder uut177 (
    .a(P_14_1),
    .b(P_15_0),
    .cin(c10),
    .cout(c37),
    .sum(s37)
  );
  FullAdder uut178 (
    .a(P_15_1),
    .b(P_16_0),
    .cin(c11),
    .cout(c38),
    .sum(s38)
  );
  FullAdder uut179 (
    .a(P_16_1),
    .b(P_17_0),
    .cin(c12),
    .cout(c39),
    .sum(s39)
  );
  AndGate uut18 (
    .a(A[3]),
    .b(B[3]),
    .y(P_3_3)
  );
  FullAdder uut180 (
    .a(P_17_1),
    .b(P_18_0),
    .cin(c13),
    .cout(c40),
    .sum(s40)
  );
  FullAdder uut181 (
    .a(P_18_1),
    .b(P_19_0),
    .cin(c14),
    .cout(c41),
    .sum(s41)
  );
  FullAdder uut182 (
    .a(P_19_1),
    .b(P_20_0),
    .cin(c15),
    .cout(c42),
    .sum(s42)
  );
  FullAdder uut183 (
    .a(P_20_1),
    .b(P_21_0),
    .cin(c16),
    .cout(c43),
    .sum(s43)
  );
  FullAdder uut184 (
    .a(P_21_1),
    .b(P_22_0),
    .cin(c17),
    .cout(c44),
    .sum(s44)
  );
  FullAdder uut185 (
    .a(P_22_1),
    .b(P_23_0),
    .cin(c18),
    .cout(c45),
    .sum(s45)
  );
  FullAdder uut186 (
    .a(P_23_1),
    .b(P_24_0),
    .cin(c19),
    .cout(c46),
    .sum(s46)
  );
  FullAdder uut187 (
    .a(P_24_1),
    .b(P_25_0),
    .cin(c20),
    .cout(c47),
    .sum(s47)
  );
  FullAdder uut188 (
    .a(P_25_1),
    .b(P_26_0),
    .cin(c21),
    .cout(c48),
    .sum(s48)
  );
  FullAdder uut189 (
    .a(P_26_1),
    .b(P_27_0),
    .cin(c22),
    .cout(c49),
    .sum(s49)
  );
  AndGate uut19 (
    .a(A[4]),
    .b(B[3]),
    .y(P_3_4)
  );
  FullAdder uut190 (
    .a(P_26_2),
    .b(P_27_1),
    .cin(c23),
    .cout(c50),
    .sum(s50)
  );
  FullAdder uut191 (
    .a(P_25_4),
    .b(P_26_3),
    .cin(P_27_2),
    .cout(c51),
    .sum(s51)
  );
  HalfAdder uut192 (
    .a(P_0_2),
    .b(P_1_1),
    .cout(c52),
    .sum(s52)
  );
  FullAdder uut193 (
    .a(P_2_1),
    .b(P_3_0),
    .cin(s25),
    .cout(c53),
    .sum(s53)
  );
  FullAdder uut194 (
    .a(s0),
    .b(c25),
    .cin(s26),
    .cout(c54),
    .sum(s54)
  );
  FullAdder uut195 (
    .a(s1),
    .b(c26),
    .cin(s27),
    .cout(c55),
    .sum(s55)
  );
  FullAdder uut196 (
    .a(s2),
    .b(c27),
    .cin(s28),
    .cout(c56),
    .sum(s56)
  );
  FullAdder uut197 (
    .a(s3),
    .b(c28),
    .cin(s29),
    .cout(c57),
    .sum(s57)
  );
  FullAdder uut198 (
    .a(s4),
    .b(c29),
    .cin(s30),
    .cout(c58),
    .sum(s58)
  );
  FullAdder uut199 (
    .a(s5),
    .b(c30),
    .cin(s31),
    .cout(c59),
    .sum(s59)
  );
  AndGate uut2 (
    .a(A[2]),
    .b(B[0]),
    .y(P_0_2)
  );
  AndGate uut20 (
    .a(A[0]),
    .b(B[4]),
    .y(P_4_0)
  );
  FullAdder uut200 (
    .a(s6),
    .b(c31),
    .cin(s32),
    .cout(c60),
    .sum(s60)
  );
  FullAdder uut201 (
    .a(s7),
    .b(c32),
    .cin(s33),
    .cout(c61),
    .sum(s61)
  );
  FullAdder uut202 (
    .a(s8),
    .b(c33),
    .cin(s34),
    .cout(c62),
    .sum(s62)
  );
  FullAdder uut203 (
    .a(s9),
    .b(c34),
    .cin(s35),
    .cout(c63),
    .sum(s63)
  );
  FullAdder uut204 (
    .a(s10),
    .b(c35),
    .cin(s36),
    .cout(c64),
    .sum(s64)
  );
  FullAdder uut205 (
    .a(s11),
    .b(c36),
    .cin(s37),
    .cout(c65),
    .sum(s65)
  );
  FullAdder uut206 (
    .a(s12),
    .b(c37),
    .cin(s38),
    .cout(c66),
    .sum(s66)
  );
  FullAdder uut207 (
    .a(s13),
    .b(c38),
    .cin(s39),
    .cout(c67),
    .sum(s67)
  );
  FullAdder uut208 (
    .a(s14),
    .b(c39),
    .cin(s40),
    .cout(c68),
    .sum(s68)
  );
  FullAdder uut209 (
    .a(s15),
    .b(c40),
    .cin(s41),
    .cout(c69),
    .sum(s69)
  );
  AndGate uut21 (
    .a(A[1]),
    .b(B[4]),
    .y(P_4_1)
  );
  FullAdder uut210 (
    .a(s16),
    .b(c41),
    .cin(s42),
    .cout(c70),
    .sum(s70)
  );
  FullAdder uut211 (
    .a(s17),
    .b(c42),
    .cin(s43),
    .cout(c71),
    .sum(s71)
  );
  FullAdder uut212 (
    .a(s18),
    .b(c43),
    .cin(s44),
    .cout(c72),
    .sum(s72)
  );
  FullAdder uut213 (
    .a(s19),
    .b(c44),
    .cin(s45),
    .cout(c73),
    .sum(s73)
  );
  FullAdder uut214 (
    .a(s20),
    .b(c45),
    .cin(s46),
    .cout(c74),
    .sum(s74)
  );
  FullAdder uut215 (
    .a(s21),
    .b(c46),
    .cin(s47),
    .cout(c75),
    .sum(s75)
  );
  FullAdder uut216 (
    .a(s22),
    .b(c47),
    .cin(s48),
    .cout(c76),
    .sum(s76)
  );
  FullAdder uut217 (
    .a(s23),
    .b(c48),
    .cin(s49),
    .cout(c77),
    .sum(s77)
  );
  FullAdder uut218 (
    .a(s24),
    .b(c49),
    .cin(s50),
    .cout(c78),
    .sum(s78)
  );
  FullAdder uut219 (
    .a(c24),
    .b(c50),
    .cin(s51),
    .cout(c79),
    .sum(s79)
  );
  AndGate uut22 (
    .a(A[2]),
    .b(B[4]),
    .y(P_4_2)
  );
  FullAdder uut220 (
    .a(P_26_4),
    .b(P_27_3),
    .cin(c51),
    .cout(c80),
    .sum(s80)
  );
  unsignedBrentKungAdder31bit uut221 (
    .A({ P_27_4, c79, c78, c77, c76, c75, c74, c73, c72, c71, c70, c69, c68, c67, c66, c65, c64, c63, c62, c61, c60, c59, c58, c57, c56, c55, c54, c53, c52, P_2_0, P_0_1 }),
    .B({ c80, s80, s79, s78, s77, s76, s75, s74, s73, s72, s71, s70, s69, s68, s67, s66, s65, s64, s63, s62, s61, s60, s59, s58, s57, s56, s55, s54, s53, s52, P_1_0 }),
    .Sum(Product[32:1])
  );
  AndGate uut23 (
    .a(A[3]),
    .b(B[4]),
    .y(P_4_3)
  );
  AndGate uut24 (
    .a(A[4]),
    .b(B[4]),
    .y(P_4_4)
  );
  AndGate uut25 (
    .a(A[0]),
    .b(B[5]),
    .y(P_5_0)
  );
  AndGate uut26 (
    .a(A[1]),
    .b(B[5]),
    .y(P_5_1)
  );
  AndGate uut27 (
    .a(A[2]),
    .b(B[5]),
    .y(P_5_2)
  );
  AndGate uut28 (
    .a(A[3]),
    .b(B[5]),
    .y(P_5_3)
  );
  AndGate uut29 (
    .a(A[4]),
    .b(B[5]),
    .y(P_5_4)
  );
  AndGate uut3 (
    .a(A[3]),
    .b(B[0]),
    .y(P_0_3)
  );
  AndGate uut30 (
    .a(A[0]),
    .b(B[6]),
    .y(P_6_0)
  );
  AndGate uut31 (
    .a(A[1]),
    .b(B[6]),
    .y(P_6_1)
  );
  AndGate uut32 (
    .a(A[2]),
    .b(B[6]),
    .y(P_6_2)
  );
  AndGate uut33 (
    .a(A[3]),
    .b(B[6]),
    .y(P_6_3)
  );
  AndGate uut34 (
    .a(A[4]),
    .b(B[6]),
    .y(P_6_4)
  );
  AndGate uut35 (
    .a(A[0]),
    .b(B[7]),
    .y(P_7_0)
  );
  AndGate uut36 (
    .a(A[1]),
    .b(B[7]),
    .y(P_7_1)
  );
  AndGate uut37 (
    .a(A[2]),
    .b(B[7]),
    .y(P_7_2)
  );
  AndGate uut38 (
    .a(A[3]),
    .b(B[7]),
    .y(P_7_3)
  );
  AndGate uut39 (
    .a(A[4]),
    .b(B[7]),
    .y(P_7_4)
  );
  AndGate uut4 (
    .a(A[4]),
    .b(B[0]),
    .y(P_0_4)
  );
  AndGate uut40 (
    .a(A[0]),
    .b(B[8]),
    .y(P_8_0)
  );
  AndGate uut41 (
    .a(A[1]),
    .b(B[8]),
    .y(P_8_1)
  );
  AndGate uut42 (
    .a(A[2]),
    .b(B[8]),
    .y(P_8_2)
  );
  AndGate uut43 (
    .a(A[3]),
    .b(B[8]),
    .y(P_8_3)
  );
  AndGate uut44 (
    .a(A[4]),
    .b(B[8]),
    .y(P_8_4)
  );
  AndGate uut45 (
    .a(A[0]),
    .b(B[9]),
    .y(P_9_0)
  );
  AndGate uut46 (
    .a(A[1]),
    .b(B[9]),
    .y(P_9_1)
  );
  AndGate uut47 (
    .a(A[2]),
    .b(B[9]),
    .y(P_9_2)
  );
  AndGate uut48 (
    .a(A[3]),
    .b(B[9]),
    .y(P_9_3)
  );
  AndGate uut49 (
    .a(A[4]),
    .b(B[9]),
    .y(P_9_4)
  );
  AndGate uut5 (
    .a(A[0]),
    .b(B[1]),
    .y(P_1_0)
  );
  AndGate uut50 (
    .a(A[0]),
    .b(B[10]),
    .y(P_10_0)
  );
  AndGate uut51 (
    .a(A[1]),
    .b(B[10]),
    .y(P_10_1)
  );
  AndGate uut52 (
    .a(A[2]),
    .b(B[10]),
    .y(P_10_2)
  );
  AndGate uut53 (
    .a(A[3]),
    .b(B[10]),
    .y(P_10_3)
  );
  AndGate uut54 (
    .a(A[4]),
    .b(B[10]),
    .y(P_10_4)
  );
  AndGate uut55 (
    .a(A[0]),
    .b(B[11]),
    .y(P_11_0)
  );
  AndGate uut56 (
    .a(A[1]),
    .b(B[11]),
    .y(P_11_1)
  );
  AndGate uut57 (
    .a(A[2]),
    .b(B[11]),
    .y(P_11_2)
  );
  AndGate uut58 (
    .a(A[3]),
    .b(B[11]),
    .y(P_11_3)
  );
  AndGate uut59 (
    .a(A[4]),
    .b(B[11]),
    .y(P_11_4)
  );
  AndGate uut6 (
    .a(A[1]),
    .b(B[1]),
    .y(P_1_1)
  );
  AndGate uut60 (
    .a(A[0]),
    .b(B[12]),
    .y(P_12_0)
  );
  AndGate uut61 (
    .a(A[1]),
    .b(B[12]),
    .y(P_12_1)
  );
  AndGate uut62 (
    .a(A[2]),
    .b(B[12]),
    .y(P_12_2)
  );
  AndGate uut63 (
    .a(A[3]),
    .b(B[12]),
    .y(P_12_3)
  );
  AndGate uut64 (
    .a(A[4]),
    .b(B[12]),
    .y(P_12_4)
  );
  AndGate uut65 (
    .a(A[0]),
    .b(B[13]),
    .y(P_13_0)
  );
  AndGate uut66 (
    .a(A[1]),
    .b(B[13]),
    .y(P_13_1)
  );
  AndGate uut67 (
    .a(A[2]),
    .b(B[13]),
    .y(P_13_2)
  );
  AndGate uut68 (
    .a(A[3]),
    .b(B[13]),
    .y(P_13_3)
  );
  AndGate uut69 (
    .a(A[4]),
    .b(B[13]),
    .y(P_13_4)
  );
  AndGate uut7 (
    .a(A[2]),
    .b(B[1]),
    .y(P_1_2)
  );
  AndGate uut70 (
    .a(A[0]),
    .b(B[14]),
    .y(P_14_0)
  );
  AndGate uut71 (
    .a(A[1]),
    .b(B[14]),
    .y(P_14_1)
  );
  AndGate uut72 (
    .a(A[2]),
    .b(B[14]),
    .y(P_14_2)
  );
  AndGate uut73 (
    .a(A[3]),
    .b(B[14]),
    .y(P_14_3)
  );
  AndGate uut74 (
    .a(A[4]),
    .b(B[14]),
    .y(P_14_4)
  );
  AndGate uut75 (
    .a(A[0]),
    .b(B[15]),
    .y(P_15_0)
  );
  AndGate uut76 (
    .a(A[1]),
    .b(B[15]),
    .y(P_15_1)
  );
  AndGate uut77 (
    .a(A[2]),
    .b(B[15]),
    .y(P_15_2)
  );
  AndGate uut78 (
    .a(A[3]),
    .b(B[15]),
    .y(P_15_3)
  );
  AndGate uut79 (
    .a(A[4]),
    .b(B[15]),
    .y(P_15_4)
  );
  AndGate uut8 (
    .a(A[3]),
    .b(B[1]),
    .y(P_1_3)
  );
  AndGate uut80 (
    .a(A[0]),
    .b(B[16]),
    .y(P_16_0)
  );
  AndGate uut81 (
    .a(A[1]),
    .b(B[16]),
    .y(P_16_1)
  );
  AndGate uut82 (
    .a(A[2]),
    .b(B[16]),
    .y(P_16_2)
  );
  AndGate uut83 (
    .a(A[3]),
    .b(B[16]),
    .y(P_16_3)
  );
  AndGate uut84 (
    .a(A[4]),
    .b(B[16]),
    .y(P_16_4)
  );
  AndGate uut85 (
    .a(A[0]),
    .b(B[17]),
    .y(P_17_0)
  );
  AndGate uut86 (
    .a(A[1]),
    .b(B[17]),
    .y(P_17_1)
  );
  AndGate uut87 (
    .a(A[2]),
    .b(B[17]),
    .y(P_17_2)
  );
  AndGate uut88 (
    .a(A[3]),
    .b(B[17]),
    .y(P_17_3)
  );
  AndGate uut89 (
    .a(A[4]),
    .b(B[17]),
    .y(P_17_4)
  );
  AndGate uut9 (
    .a(A[4]),
    .b(B[1]),
    .y(P_1_4)
  );
  AndGate uut90 (
    .a(A[0]),
    .b(B[18]),
    .y(P_18_0)
  );
  AndGate uut91 (
    .a(A[1]),
    .b(B[18]),
    .y(P_18_1)
  );
  AndGate uut92 (
    .a(A[2]),
    .b(B[18]),
    .y(P_18_2)
  );
  AndGate uut93 (
    .a(A[3]),
    .b(B[18]),
    .y(P_18_3)
  );
  AndGate uut94 (
    .a(A[4]),
    .b(B[18]),
    .y(P_18_4)
  );
  AndGate uut95 (
    .a(A[0]),
    .b(B[19]),
    .y(P_19_0)
  );
  AndGate uut96 (
    .a(A[1]),
    .b(B[19]),
    .y(P_19_1)
  );
  AndGate uut97 (
    .a(A[2]),
    .b(B[19]),
    .y(P_19_2)
  );
  AndGate uut98 (
    .a(A[3]),
    .b(B[19]),
    .y(P_19_3)
  );
  AndGate uut99 (
    .a(A[4]),
    .b(B[19]),
    .y(P_19_4)
  );
  assign Product[0] = P_0_0;
endmodule

module XorGate(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  XOR2xp5_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(Y)
  );
endmodule

module unsignedBrentKungAdder31bit(A, B, Sum);
  input [30:0] A;
  wire [30:0] A;
  input [30:0] B;
  wire [30:0] B;
  wire G_0_0;
  wire G_0_1;
  wire G_0_10;
  wire G_0_11;
  wire G_0_12;
  wire G_0_13;
  wire G_0_14;
  wire G_0_15;
  wire G_0_16;
  wire G_0_17;
  wire G_0_18;
  wire G_0_19;
  wire G_0_2;
  wire G_0_20;
  wire G_0_21;
  wire G_0_22;
  wire G_0_23;
  wire G_0_24;
  wire G_0_25;
  wire G_0_26;
  wire G_0_27;
  wire G_0_28;
  wire G_0_29;
  wire G_0_3;
  wire G_0_30;
  wire G_0_4;
  wire G_0_5;
  wire G_0_6;
  wire G_0_7;
  wire G_0_8;
  wire G_0_9;
  wire G_1_1;
  wire G_1_11;
  wire G_1_13;
  wire G_1_15;
  wire G_1_17;
  wire G_1_19;
  wire G_1_21;
  wire G_1_23;
  wire G_1_25;
  wire G_1_27;
  wire G_1_29;
  wire G_1_3;
  wire G_1_5;
  wire G_1_7;
  wire G_1_9;
  wire G_2_11;
  wire G_2_15;
  wire G_2_19;
  wire G_2_23;
  wire G_2_27;
  wire G_2_3;
  wire G_2_7;
  wire G_3_15;
  wire G_3_23;
  wire G_3_7;
  wire G_4_15;
  wire G_6_23;
  wire G_7_11;
  wire G_7_19;
  wire G_7_27;
  wire G_8_13;
  wire G_8_17;
  wire G_8_21;
  wire G_8_25;
  wire G_8_29;
  wire G_8_5;
  wire G_8_9;
  wire G_9_10;
  wire G_9_12;
  wire G_9_14;
  wire G_9_16;
  wire G_9_18;
  wire G_9_2;
  wire G_9_20;
  wire G_9_22;
  wire G_9_24;
  wire G_9_26;
  wire G_9_28;
  wire G_9_30;
  wire G_9_4;
  wire G_9_6;
  wire G_9_8;
  wire P_0_0;
  wire P_0_1;
  wire P_0_10;
  wire P_0_11;
  wire P_0_12;
  wire P_0_13;
  wire P_0_14;
  wire P_0_15;
  wire P_0_16;
  wire P_0_17;
  wire P_0_18;
  wire P_0_19;
  wire P_0_2;
  wire P_0_20;
  wire P_0_21;
  wire P_0_22;
  wire P_0_23;
  wire P_0_24;
  wire P_0_25;
  wire P_0_26;
  wire P_0_27;
  wire P_0_28;
  wire P_0_29;
  wire P_0_3;
  wire P_0_30;
  wire P_0_4;
  wire P_0_5;
  wire P_0_6;
  wire P_0_7;
  wire P_0_8;
  wire P_0_9;
  wire P_1_1;
  wire P_1_11;
  wire P_1_13;
  wire P_1_15;
  wire P_1_17;
  wire P_1_19;
  wire P_1_21;
  wire P_1_23;
  wire P_1_25;
  wire P_1_27;
  wire P_1_29;
  wire P_1_3;
  wire P_1_5;
  wire P_1_7;
  wire P_1_9;
  wire P_2_11;
  wire P_2_15;
  wire P_2_19;
  wire P_2_23;
  wire P_2_27;
  wire P_2_3;
  wire P_2_7;
  wire P_3_15;
  wire P_3_23;
  wire P_3_7;
  wire P_4_15;
  wire P_6_23;
  wire P_7_11;
  wire P_7_19;
  wire P_7_27;
  wire P_8_13;
  wire P_8_17;
  wire P_8_21;
  wire P_8_25;
  wire P_8_29;
  wire P_8_5;
  wire P_8_9;
  wire P_9_10;
  wire P_9_12;
  wire P_9_14;
  wire P_9_16;
  wire P_9_18;
  wire P_9_2;
  wire P_9_20;
  wire P_9_22;
  wire P_9_24;
  wire P_9_26;
  wire P_9_28;
  wire P_9_30;
  wire P_9_4;
  wire P_9_6;
  wire P_9_8;
  output [31:0] Sum;
  wire [31:0] Sum;
  BitwisePG uut0 (
    .A(A[0]),
    .B(B[0]),
    .G(G_0_0),
    .P(P_0_0)
  );
  BitwisePG uut1 (
    .A(A[1]),
    .B(B[1]),
    .G(G_0_1),
    .P(P_0_1)
  );
  BitwisePG uut10 (
    .A(A[10]),
    .B(B[10]),
    .G(G_0_10),
    .P(P_0_10)
  );
  XorGate uut100 (
    .A(P_0_18),
    .B(G_8_17),
    .Y(Sum[18])
  );
  XorGate uut101 (
    .A(P_0_19),
    .B(G_9_18),
    .Y(Sum[19])
  );
  XorGate uut102 (
    .A(P_0_20),
    .B(G_7_19),
    .Y(Sum[20])
  );
  XorGate uut103 (
    .A(P_0_21),
    .B(G_9_20),
    .Y(Sum[21])
  );
  XorGate uut104 (
    .A(P_0_22),
    .B(G_8_21),
    .Y(Sum[22])
  );
  XorGate uut105 (
    .A(P_0_23),
    .B(G_9_22),
    .Y(Sum[23])
  );
  XorGate uut106 (
    .A(P_0_24),
    .B(G_6_23),
    .Y(Sum[24])
  );
  XorGate uut107 (
    .A(P_0_25),
    .B(G_9_24),
    .Y(Sum[25])
  );
  XorGate uut108 (
    .A(P_0_26),
    .B(G_8_25),
    .Y(Sum[26])
  );
  XorGate uut109 (
    .A(P_0_27),
    .B(G_9_26),
    .Y(Sum[27])
  );
  BitwisePG uut11 (
    .A(A[11]),
    .B(B[11]),
    .G(G_0_11),
    .P(P_0_11)
  );
  XorGate uut110 (
    .A(P_0_28),
    .B(G_7_27),
    .Y(Sum[28])
  );
  XorGate uut111 (
    .A(P_0_29),
    .B(G_9_28),
    .Y(Sum[29])
  );
  XorGate uut112 (
    .A(P_0_30),
    .B(G_8_29),
    .Y(Sum[30])
  );
  BitwisePG uut12 (
    .A(A[12]),
    .B(B[12]),
    .G(G_0_12),
    .P(P_0_12)
  );
  BitwisePG uut13 (
    .A(A[13]),
    .B(B[13]),
    .G(G_0_13),
    .P(P_0_13)
  );
  BitwisePG uut14 (
    .A(A[14]),
    .B(B[14]),
    .G(G_0_14),
    .P(P_0_14)
  );
  BitwisePG uut15 (
    .A(A[15]),
    .B(B[15]),
    .G(G_0_15),
    .P(P_0_15)
  );
  BitwisePG uut16 (
    .A(A[16]),
    .B(B[16]),
    .G(G_0_16),
    .P(P_0_16)
  );
  BitwisePG uut17 (
    .A(A[17]),
    .B(B[17]),
    .G(G_0_17),
    .P(P_0_17)
  );
  BitwisePG uut18 (
    .A(A[18]),
    .B(B[18]),
    .G(G_0_18),
    .P(P_0_18)
  );
  BitwisePG uut19 (
    .A(A[19]),
    .B(B[19]),
    .G(G_0_19),
    .P(P_0_19)
  );
  BitwisePG uut2 (
    .A(A[2]),
    .B(B[2]),
    .G(G_0_2),
    .P(P_0_2)
  );
  BitwisePG uut20 (
    .A(A[20]),
    .B(B[20]),
    .G(G_0_20),
    .P(P_0_20)
  );
  BitwisePG uut21 (
    .A(A[21]),
    .B(B[21]),
    .G(G_0_21),
    .P(P_0_21)
  );
  BitwisePG uut22 (
    .A(A[22]),
    .B(B[22]),
    .G(G_0_22),
    .P(P_0_22)
  );
  BitwisePG uut23 (
    .A(A[23]),
    .B(B[23]),
    .G(G_0_23),
    .P(P_0_23)
  );
  BitwisePG uut24 (
    .A(A[24]),
    .B(B[24]),
    .G(G_0_24),
    .P(P_0_24)
  );
  BitwisePG uut25 (
    .A(A[25]),
    .B(B[25]),
    .G(G_0_25),
    .P(P_0_25)
  );
  BitwisePG uut26 (
    .A(A[26]),
    .B(B[26]),
    .G(G_0_26),
    .P(P_0_26)
  );
  BitwisePG uut27 (
    .A(A[27]),
    .B(B[27]),
    .G(G_0_27),
    .P(P_0_27)
  );
  BitwisePG uut28 (
    .A(A[28]),
    .B(B[28]),
    .G(G_0_28),
    .P(P_0_28)
  );
  BitwisePG uut29 (
    .A(A[29]),
    .B(B[29]),
    .G(G_0_29),
    .P(P_0_29)
  );
  BitwisePG uut3 (
    .A(A[3]),
    .B(B[3]),
    .G(G_0_3),
    .P(P_0_3)
  );
  BitwisePG uut30 (
    .A(A[30]),
    .B(B[30]),
    .G(G_0_30),
    .P(P_0_30)
  );
  GrayCell uut31 (
    .Cin(G_0_0),
    .G(G_1_1),
    .Gi(G_0_1),
    .P(P_1_1),
    .Pi(P_0_1)
  );
  BlackCell uut32 (
    .Cin(G_0_2),
    .G(G_1_3),
    .Gi(G_0_3),
    .P(P_1_3),
    .Pi(P_0_3),
    .Pj(P_0_2)
  );
  BlackCell uut33 (
    .Cin(G_0_4),
    .G(G_1_5),
    .Gi(G_0_5),
    .P(P_1_5),
    .Pi(P_0_5),
    .Pj(P_0_4)
  );
  BlackCell uut34 (
    .Cin(G_0_6),
    .G(G_1_7),
    .Gi(G_0_7),
    .P(P_1_7),
    .Pi(P_0_7),
    .Pj(P_0_6)
  );
  BlackCell uut35 (
    .Cin(G_0_8),
    .G(G_1_9),
    .Gi(G_0_9),
    .P(P_1_9),
    .Pi(P_0_9),
    .Pj(P_0_8)
  );
  BlackCell uut36 (
    .Cin(G_0_10),
    .G(G_1_11),
    .Gi(G_0_11),
    .P(P_1_11),
    .Pi(P_0_11),
    .Pj(P_0_10)
  );
  BlackCell uut37 (
    .Cin(G_0_12),
    .G(G_1_13),
    .Gi(G_0_13),
    .P(P_1_13),
    .Pi(P_0_13),
    .Pj(P_0_12)
  );
  BlackCell uut38 (
    .Cin(G_0_14),
    .G(G_1_15),
    .Gi(G_0_15),
    .P(P_1_15),
    .Pi(P_0_15),
    .Pj(P_0_14)
  );
  BlackCell uut39 (
    .Cin(G_0_16),
    .G(G_1_17),
    .Gi(G_0_17),
    .P(P_1_17),
    .Pi(P_0_17),
    .Pj(P_0_16)
  );
  BitwisePG uut4 (
    .A(A[4]),
    .B(B[4]),
    .G(G_0_4),
    .P(P_0_4)
  );
  BlackCell uut40 (
    .Cin(G_0_18),
    .G(G_1_19),
    .Gi(G_0_19),
    .P(P_1_19),
    .Pi(P_0_19),
    .Pj(P_0_18)
  );
  BlackCell uut41 (
    .Cin(G_0_20),
    .G(G_1_21),
    .Gi(G_0_21),
    .P(P_1_21),
    .Pi(P_0_21),
    .Pj(P_0_20)
  );
  BlackCell uut42 (
    .Cin(G_0_22),
    .G(G_1_23),
    .Gi(G_0_23),
    .P(P_1_23),
    .Pi(P_0_23),
    .Pj(P_0_22)
  );
  BlackCell uut43 (
    .Cin(G_0_24),
    .G(G_1_25),
    .Gi(G_0_25),
    .P(P_1_25),
    .Pi(P_0_25),
    .Pj(P_0_24)
  );
  BlackCell uut44 (
    .Cin(G_0_26),
    .G(G_1_27),
    .Gi(G_0_27),
    .P(P_1_27),
    .Pi(P_0_27),
    .Pj(P_0_26)
  );
  BlackCell uut45 (
    .Cin(G_0_28),
    .G(G_1_29),
    .Gi(G_0_29),
    .P(P_1_29),
    .Pi(P_0_29),
    .Pj(P_0_28)
  );
  GrayCell uut46 (
    .Cin(G_1_1),
    .G(G_2_3),
    .Gi(G_1_3),
    .P(P_2_3),
    .Pi(P_1_3)
  );
  BlackCell uut47 (
    .Cin(G_1_5),
    .G(G_2_7),
    .Gi(G_1_7),
    .P(P_2_7),
    .Pi(P_1_7),
    .Pj(P_1_5)
  );
  BlackCell uut48 (
    .Cin(G_1_9),
    .G(G_2_11),
    .Gi(G_1_11),
    .P(P_2_11),
    .Pi(P_1_11),
    .Pj(P_1_9)
  );
  BlackCell uut49 (
    .Cin(G_1_13),
    .G(G_2_15),
    .Gi(G_1_15),
    .P(P_2_15),
    .Pi(P_1_15),
    .Pj(P_1_13)
  );
  BitwisePG uut5 (
    .A(A[5]),
    .B(B[5]),
    .G(G_0_5),
    .P(P_0_5)
  );
  BlackCell uut50 (
    .Cin(G_1_17),
    .G(G_2_19),
    .Gi(G_1_19),
    .P(P_2_19),
    .Pi(P_1_19),
    .Pj(P_1_17)
  );
  BlackCell uut51 (
    .Cin(G_1_21),
    .G(G_2_23),
    .Gi(G_1_23),
    .P(P_2_23),
    .Pi(P_1_23),
    .Pj(P_1_21)
  );
  BlackCell uut52 (
    .Cin(G_1_25),
    .G(G_2_27),
    .Gi(G_1_27),
    .P(P_2_27),
    .Pi(P_1_27),
    .Pj(P_1_25)
  );
  GrayCell uut53 (
    .Cin(G_2_3),
    .G(G_3_7),
    .Gi(G_2_7),
    .P(P_3_7),
    .Pi(P_2_7)
  );
  BlackCell uut54 (
    .Cin(G_2_11),
    .G(G_3_15),
    .Gi(G_2_15),
    .P(P_3_15),
    .Pi(P_2_15),
    .Pj(P_2_11)
  );
  BlackCell uut55 (
    .Cin(G_2_19),
    .G(G_3_23),
    .Gi(G_2_23),
    .P(P_3_23),
    .Pi(P_2_23),
    .Pj(P_2_19)
  );
  GrayCell uut56 (
    .Cin(G_3_7),
    .G(G_4_15),
    .Gi(G_3_15),
    .P(P_4_15),
    .Pi(P_3_15)
  );
  GrayCell uut57 (
    .Cin(G_4_15),
    .G(G_6_23),
    .Gi(G_3_23),
    .P(P_6_23),
    .Pi(P_3_23)
  );
  GrayCell uut58 (
    .Cin(G_3_7),
    .G(G_7_11),
    .Gi(G_2_11),
    .P(P_7_11),
    .Pi(P_2_11)
  );
  GrayCell uut59 (
    .Cin(G_4_15),
    .G(G_7_19),
    .Gi(G_2_19),
    .P(P_7_19),
    .Pi(P_2_19)
  );
  BitwisePG uut6 (
    .A(A[6]),
    .B(B[6]),
    .G(G_0_6),
    .P(P_0_6)
  );
  GrayCell uut60 (
    .Cin(G_6_23),
    .G(G_7_27),
    .Gi(G_2_27),
    .P(P_7_27),
    .Pi(P_2_27)
  );
  GrayCell uut61 (
    .Cin(G_2_3),
    .G(G_8_5),
    .Gi(G_1_5),
    .P(P_8_5),
    .Pi(P_1_5)
  );
  GrayCell uut62 (
    .Cin(G_3_7),
    .G(G_8_9),
    .Gi(G_1_9),
    .P(P_8_9),
    .Pi(P_1_9)
  );
  GrayCell uut63 (
    .Cin(G_7_11),
    .G(G_8_13),
    .Gi(G_1_13),
    .P(P_8_13),
    .Pi(P_1_13)
  );
  GrayCell uut64 (
    .Cin(G_4_15),
    .G(G_8_17),
    .Gi(G_1_17),
    .P(P_8_17),
    .Pi(P_1_17)
  );
  GrayCell uut65 (
    .Cin(G_7_19),
    .G(G_8_21),
    .Gi(G_1_21),
    .P(P_8_21),
    .Pi(P_1_21)
  );
  GrayCell uut66 (
    .Cin(G_6_23),
    .G(G_8_25),
    .Gi(G_1_25),
    .P(P_8_25),
    .Pi(P_1_25)
  );
  GrayCell uut67 (
    .Cin(G_7_27),
    .G(G_8_29),
    .Gi(G_1_29),
    .P(P_8_29),
    .Pi(P_1_29)
  );
  GrayCell uut68 (
    .Cin(G_1_1),
    .G(G_9_2),
    .Gi(G_0_2),
    .P(P_9_2),
    .Pi(P_0_2)
  );
  GrayCell uut69 (
    .Cin(G_2_3),
    .G(G_9_4),
    .Gi(G_0_4),
    .P(P_9_4),
    .Pi(P_0_4)
  );
  BitwisePG uut7 (
    .A(A[7]),
    .B(B[7]),
    .G(G_0_7),
    .P(P_0_7)
  );
  GrayCell uut70 (
    .Cin(G_8_5),
    .G(G_9_6),
    .Gi(G_0_6),
    .P(P_9_6),
    .Pi(P_0_6)
  );
  GrayCell uut71 (
    .Cin(G_3_7),
    .G(G_9_8),
    .Gi(G_0_8),
    .P(P_9_8),
    .Pi(P_0_8)
  );
  GrayCell uut72 (
    .Cin(G_8_9),
    .G(G_9_10),
    .Gi(G_0_10),
    .P(P_9_10),
    .Pi(P_0_10)
  );
  GrayCell uut73 (
    .Cin(G_7_11),
    .G(G_9_12),
    .Gi(G_0_12),
    .P(P_9_12),
    .Pi(P_0_12)
  );
  GrayCell uut74 (
    .Cin(G_8_13),
    .G(G_9_14),
    .Gi(G_0_14),
    .P(P_9_14),
    .Pi(P_0_14)
  );
  GrayCell uut75 (
    .Cin(G_4_15),
    .G(G_9_16),
    .Gi(G_0_16),
    .P(P_9_16),
    .Pi(P_0_16)
  );
  GrayCell uut76 (
    .Cin(G_8_17),
    .G(G_9_18),
    .Gi(G_0_18),
    .P(P_9_18),
    .Pi(P_0_18)
  );
  GrayCell uut77 (
    .Cin(G_7_19),
    .G(G_9_20),
    .Gi(G_0_20),
    .P(P_9_20),
    .Pi(P_0_20)
  );
  GrayCell uut78 (
    .Cin(G_8_21),
    .G(G_9_22),
    .Gi(G_0_22),
    .P(P_9_22),
    .Pi(P_0_22)
  );
  GrayCell uut79 (
    .Cin(G_6_23),
    .G(G_9_24),
    .Gi(G_0_24),
    .P(P_9_24),
    .Pi(P_0_24)
  );
  BitwisePG uut8 (
    .A(A[8]),
    .B(B[8]),
    .G(G_0_8),
    .P(P_0_8)
  );
  GrayCell uut80 (
    .Cin(G_8_25),
    .G(G_9_26),
    .Gi(G_0_26),
    .P(P_9_26),
    .Pi(P_0_26)
  );
  GrayCell uut81 (
    .Cin(G_7_27),
    .G(G_9_28),
    .Gi(G_0_28),
    .P(P_9_28),
    .Pi(P_0_28)
  );
  GrayCell uut82 (
    .Cin(G_8_29),
    .G(G_9_30),
    .Gi(G_0_30),
    .P(P_9_30),
    .Pi(P_0_30)
  );
  XorGate uut83 (
    .A(P_0_1),
    .B(G_0_0),
    .Y(Sum[1])
  );
  XorGate uut84 (
    .A(P_0_2),
    .B(G_1_1),
    .Y(Sum[2])
  );
  XorGate uut85 (
    .A(P_0_3),
    .B(G_9_2),
    .Y(Sum[3])
  );
  XorGate uut86 (
    .A(P_0_4),
    .B(G_2_3),
    .Y(Sum[4])
  );
  XorGate uut87 (
    .A(P_0_5),
    .B(G_9_4),
    .Y(Sum[5])
  );
  XorGate uut88 (
    .A(P_0_6),
    .B(G_8_5),
    .Y(Sum[6])
  );
  XorGate uut89 (
    .A(P_0_7),
    .B(G_9_6),
    .Y(Sum[7])
  );
  BitwisePG uut9 (
    .A(A[9]),
    .B(B[9]),
    .G(G_0_9),
    .P(P_0_9)
  );
  XorGate uut90 (
    .A(P_0_8),
    .B(G_3_7),
    .Y(Sum[8])
  );
  XorGate uut91 (
    .A(P_0_9),
    .B(G_9_8),
    .Y(Sum[9])
  );
  XorGate uut92 (
    .A(P_0_10),
    .B(G_8_9),
    .Y(Sum[10])
  );
  XorGate uut93 (
    .A(P_0_11),
    .B(G_9_10),
    .Y(Sum[11])
  );
  XorGate uut94 (
    .A(P_0_12),
    .B(G_7_11),
    .Y(Sum[12])
  );
  XorGate uut95 (
    .A(P_0_13),
    .B(G_9_12),
    .Y(Sum[13])
  );
  XorGate uut96 (
    .A(P_0_14),
    .B(G_8_13),
    .Y(Sum[14])
  );
  XorGate uut97 (
    .A(P_0_15),
    .B(G_9_14),
    .Y(Sum[15])
  );
  XorGate uut98 (
    .A(P_0_16),
    .B(G_4_15),
    .Y(Sum[16])
  );
  XorGate uut99 (
    .A(P_0_17),
    .B(G_9_16),
    .Y(Sum[17])
  );
  assign { Sum[31], Sum[0] } = { G_9_30, P_0_0 };
endmodule
