/* Generated by Yosys 0.53+39 (git sha1 388955031, g++ 12.2.0-14 -fPIC -O3) */

module AndGate(a, b, y);
  input a;
  wire a;
  input b;
  wire b;
  output y;
  wire y;
  AND2x2_ASAP7_75t_R _0_ (
    .A(b),
    .B(a),
    .Y(y)
  );
endmodule

module BitwisePG(A, B, P, G);
  input A;
  wire A;
  input B;
  wire B;
  output G;
  wire G;
  output P;
  wire P;
  AND2x2_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(G)
  );
  XOR2xp5_ASAP7_75t_R _1_ (
    .A(B),
    .B(A),
    .Y(P)
  );
endmodule

module BlackCell(Pi, Gi, Cin, Pj, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  input Pj;
  wire Pj;
  AO21x1_ASAP7_75t_R _0_ (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  AND2x2_ASAP7_75t_R _1_ (
    .A(Pi),
    .B(Pj),
    .Y(P)
  );
endmodule

module FullAdder(a, b, cin, sum, cout);
  wire _0_;
  wire _1_;
  input a;
  wire a;
  input b;
  wire b;
  input cin;
  wire cin;
  output cout;
  wire cout;
  output sum;
  wire sum;
  MAJx2_ASAP7_75t_R _2_ (
    .A(b),
    .B(a),
    .C(cin),
    .Y(cout)
  );
  NOR3xp33_ASAP7_75t_R _3_ (
    .A(b),
    .B(a),
    .C(cin),
    .Y(_0_)
  );
  NAND3xp33_ASAP7_75t_R _4_ (
    .A(b),
    .B(a),
    .C(cin),
    .Y(_1_)
  );
  OAI21xp33_ASAP7_75t_R _5_ (
    .A1(cout),
    .A2(_0_),
    .B(_1_),
    .Y(sum)
  );
endmodule

module GrayCell(Pi, Gi, Cin, P, G);
  input Cin;
  wire Cin;
  output G;
  wire G;
  input Gi;
  wire Gi;
  output P;
  wire P;
  input Pi;
  wire Pi;
  AO21x1_ASAP7_75t_R _0_ (
    .A1(Cin),
    .A2(Pi),
    .B(Gi),
    .Y(G)
  );
  assign P = Pi;
endmodule

module HalfAdder(a, b, sum, cout);
  input a;
  wire a;
  input b;
  wire b;
  output cout;
  wire cout;
  output sum;
  wire sum;
  AND2x2_ASAP7_75t_R _0_ (
    .A(b),
    .B(a),
    .Y(cout)
  );
  XOR2xp5_ASAP7_75t_R _1_ (
    .A(b),
    .B(a),
    .Y(sum)
  );
endmodule

module NR_5_16(A, B, Product);
  input [4:0] A;
  wire [4:0] A;
  input [15:0] B;
  wire [15:0] B;
  wire P_0_0;
  wire P_0_1;
  wire P_0_2;
  wire P_0_3;
  wire P_0_4;
  wire P_10_0;
  wire P_10_1;
  wire P_10_2;
  wire P_10_3;
  wire P_10_4;
  wire P_11_0;
  wire P_11_1;
  wire P_11_2;
  wire P_11_3;
  wire P_11_4;
  wire P_12_0;
  wire P_12_1;
  wire P_12_2;
  wire P_12_3;
  wire P_12_4;
  wire P_13_0;
  wire P_13_1;
  wire P_13_2;
  wire P_13_3;
  wire P_13_4;
  wire P_14_0;
  wire P_14_1;
  wire P_14_2;
  wire P_14_3;
  wire P_14_4;
  wire P_15_0;
  wire P_15_1;
  wire P_15_2;
  wire P_15_3;
  wire P_15_4;
  wire P_1_0;
  wire P_1_1;
  wire P_1_2;
  wire P_1_3;
  wire P_1_4;
  wire P_2_0;
  wire P_2_1;
  wire P_2_2;
  wire P_2_3;
  wire P_2_4;
  wire P_3_0;
  wire P_3_1;
  wire P_3_2;
  wire P_3_3;
  wire P_3_4;
  wire P_4_0;
  wire P_4_1;
  wire P_4_2;
  wire P_4_3;
  wire P_4_4;
  wire P_5_0;
  wire P_5_1;
  wire P_5_2;
  wire P_5_3;
  wire P_5_4;
  wire P_6_0;
  wire P_6_1;
  wire P_6_2;
  wire P_6_3;
  wire P_6_4;
  wire P_7_0;
  wire P_7_1;
  wire P_7_2;
  wire P_7_3;
  wire P_7_4;
  wire P_8_0;
  wire P_8_1;
  wire P_8_2;
  wire P_8_3;
  wire P_8_4;
  wire P_9_0;
  wire P_9_1;
  wire P_9_2;
  wire P_9_3;
  wire P_9_4;
  output [20:0] Product;
  wire [20:0] Product;
  wire c0;
  wire c1;
  wire c10;
  wire c11;
  wire c12;
  wire c13;
  wire c14;
  wire c15;
  wire c16;
  wire c17;
  wire c18;
  wire c19;
  wire c2;
  wire c20;
  wire c21;
  wire c22;
  wire c23;
  wire c24;
  wire c25;
  wire c26;
  wire c27;
  wire c28;
  wire c29;
  wire c3;
  wire c30;
  wire c31;
  wire c32;
  wire c33;
  wire c34;
  wire c35;
  wire c36;
  wire c37;
  wire c38;
  wire c39;
  wire c4;
  wire c40;
  wire c41;
  wire c42;
  wire c43;
  wire c44;
  wire c5;
  wire c6;
  wire c7;
  wire c8;
  wire c9;
  wire s0;
  wire s1;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire s15;
  wire s16;
  wire s17;
  wire s18;
  wire s19;
  wire s2;
  wire s20;
  wire s21;
  wire s22;
  wire s23;
  wire s24;
  wire s25;
  wire s26;
  wire s27;
  wire s28;
  wire s29;
  wire s3;
  wire s30;
  wire s31;
  wire s32;
  wire s33;
  wire s34;
  wire s35;
  wire s36;
  wire s37;
  wire s38;
  wire s39;
  wire s4;
  wire s40;
  wire s41;
  wire s42;
  wire s43;
  wire s44;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  AndGate uut0 (
    .a(A[0]),
    .b(B[0]),
    .y(P_0_0)
  );
  AndGate uut1 (
    .a(A[1]),
    .b(B[0]),
    .y(P_0_1)
  );
  AndGate uut10 (
    .a(A[0]),
    .b(B[2]),
    .y(P_2_0)
  );
  FullAdder uut100 (
    .a(P_9_1),
    .b(P_10_0),
    .cin(c5),
    .cout(c20),
    .sum(s20)
  );
  FullAdder uut101 (
    .a(P_10_1),
    .b(P_11_0),
    .cin(c6),
    .cout(c21),
    .sum(s21)
  );
  FullAdder uut102 (
    .a(P_11_1),
    .b(P_12_0),
    .cin(c7),
    .cout(c22),
    .sum(s22)
  );
  FullAdder uut103 (
    .a(P_12_1),
    .b(P_13_0),
    .cin(c8),
    .cout(c23),
    .sum(s23)
  );
  FullAdder uut104 (
    .a(P_13_1),
    .b(P_14_0),
    .cin(c9),
    .cout(c24),
    .sum(s24)
  );
  FullAdder uut105 (
    .a(P_14_1),
    .b(P_15_0),
    .cin(c10),
    .cout(c25),
    .sum(s25)
  );
  FullAdder uut106 (
    .a(P_14_2),
    .b(P_15_1),
    .cin(c11),
    .cout(c26),
    .sum(s26)
  );
  FullAdder uut107 (
    .a(P_13_4),
    .b(P_14_3),
    .cin(P_15_2),
    .cout(c27),
    .sum(s27)
  );
  HalfAdder uut108 (
    .a(P_0_2),
    .b(P_1_1),
    .cout(c28),
    .sum(s28)
  );
  FullAdder uut109 (
    .a(P_2_1),
    .b(P_3_0),
    .cin(s13),
    .cout(c29),
    .sum(s29)
  );
  AndGate uut11 (
    .a(A[1]),
    .b(B[2]),
    .y(P_2_1)
  );
  FullAdder uut110 (
    .a(s0),
    .b(c13),
    .cin(s14),
    .cout(c30),
    .sum(s30)
  );
  FullAdder uut111 (
    .a(s1),
    .b(c14),
    .cin(s15),
    .cout(c31),
    .sum(s31)
  );
  FullAdder uut112 (
    .a(s2),
    .b(c15),
    .cin(s16),
    .cout(c32),
    .sum(s32)
  );
  FullAdder uut113 (
    .a(s3),
    .b(c16),
    .cin(s17),
    .cout(c33),
    .sum(s33)
  );
  FullAdder uut114 (
    .a(s4),
    .b(c17),
    .cin(s18),
    .cout(c34),
    .sum(s34)
  );
  FullAdder uut115 (
    .a(s5),
    .b(c18),
    .cin(s19),
    .cout(c35),
    .sum(s35)
  );
  FullAdder uut116 (
    .a(s6),
    .b(c19),
    .cin(s20),
    .cout(c36),
    .sum(s36)
  );
  FullAdder uut117 (
    .a(s7),
    .b(c20),
    .cin(s21),
    .cout(c37),
    .sum(s37)
  );
  FullAdder uut118 (
    .a(s8),
    .b(c21),
    .cin(s22),
    .cout(c38),
    .sum(s38)
  );
  FullAdder uut119 (
    .a(s9),
    .b(c22),
    .cin(s23),
    .cout(c39),
    .sum(s39)
  );
  AndGate uut12 (
    .a(A[2]),
    .b(B[2]),
    .y(P_2_2)
  );
  FullAdder uut120 (
    .a(s10),
    .b(c23),
    .cin(s24),
    .cout(c40),
    .sum(s40)
  );
  FullAdder uut121 (
    .a(s11),
    .b(c24),
    .cin(s25),
    .cout(c41),
    .sum(s41)
  );
  FullAdder uut122 (
    .a(s12),
    .b(c25),
    .cin(s26),
    .cout(c42),
    .sum(s42)
  );
  FullAdder uut123 (
    .a(c12),
    .b(c26),
    .cin(s27),
    .cout(c43),
    .sum(s43)
  );
  FullAdder uut124 (
    .a(P_14_4),
    .b(P_15_3),
    .cin(c27),
    .cout(c44),
    .sum(s44)
  );
  unsignedBrentKungAdder19bit uut125 (
    .A({ P_15_4, c43, c42, c41, c40, c39, c38, c37, c36, c35, c34, c33, c32, c31, c30, c29, c28, P_2_0, P_0_1 }),
    .B({ c44, s44, s43, s42, s41, s40, s39, s38, s37, s36, s35, s34, s33, s32, s31, s30, s29, s28, P_1_0 }),
    .Sum(Product[20:1])
  );
  AndGate uut13 (
    .a(A[3]),
    .b(B[2]),
    .y(P_2_3)
  );
  AndGate uut14 (
    .a(A[4]),
    .b(B[2]),
    .y(P_2_4)
  );
  AndGate uut15 (
    .a(A[0]),
    .b(B[3]),
    .y(P_3_0)
  );
  AndGate uut16 (
    .a(A[1]),
    .b(B[3]),
    .y(P_3_1)
  );
  AndGate uut17 (
    .a(A[2]),
    .b(B[3]),
    .y(P_3_2)
  );
  AndGate uut18 (
    .a(A[3]),
    .b(B[3]),
    .y(P_3_3)
  );
  AndGate uut19 (
    .a(A[4]),
    .b(B[3]),
    .y(P_3_4)
  );
  AndGate uut2 (
    .a(A[2]),
    .b(B[0]),
    .y(P_0_2)
  );
  AndGate uut20 (
    .a(A[0]),
    .b(B[4]),
    .y(P_4_0)
  );
  AndGate uut21 (
    .a(A[1]),
    .b(B[4]),
    .y(P_4_1)
  );
  AndGate uut22 (
    .a(A[2]),
    .b(B[4]),
    .y(P_4_2)
  );
  AndGate uut23 (
    .a(A[3]),
    .b(B[4]),
    .y(P_4_3)
  );
  AndGate uut24 (
    .a(A[4]),
    .b(B[4]),
    .y(P_4_4)
  );
  AndGate uut25 (
    .a(A[0]),
    .b(B[5]),
    .y(P_5_0)
  );
  AndGate uut26 (
    .a(A[1]),
    .b(B[5]),
    .y(P_5_1)
  );
  AndGate uut27 (
    .a(A[2]),
    .b(B[5]),
    .y(P_5_2)
  );
  AndGate uut28 (
    .a(A[3]),
    .b(B[5]),
    .y(P_5_3)
  );
  AndGate uut29 (
    .a(A[4]),
    .b(B[5]),
    .y(P_5_4)
  );
  AndGate uut3 (
    .a(A[3]),
    .b(B[0]),
    .y(P_0_3)
  );
  AndGate uut30 (
    .a(A[0]),
    .b(B[6]),
    .y(P_6_0)
  );
  AndGate uut31 (
    .a(A[1]),
    .b(B[6]),
    .y(P_6_1)
  );
  AndGate uut32 (
    .a(A[2]),
    .b(B[6]),
    .y(P_6_2)
  );
  AndGate uut33 (
    .a(A[3]),
    .b(B[6]),
    .y(P_6_3)
  );
  AndGate uut34 (
    .a(A[4]),
    .b(B[6]),
    .y(P_6_4)
  );
  AndGate uut35 (
    .a(A[0]),
    .b(B[7]),
    .y(P_7_0)
  );
  AndGate uut36 (
    .a(A[1]),
    .b(B[7]),
    .y(P_7_1)
  );
  AndGate uut37 (
    .a(A[2]),
    .b(B[7]),
    .y(P_7_2)
  );
  AndGate uut38 (
    .a(A[3]),
    .b(B[7]),
    .y(P_7_3)
  );
  AndGate uut39 (
    .a(A[4]),
    .b(B[7]),
    .y(P_7_4)
  );
  AndGate uut4 (
    .a(A[4]),
    .b(B[0]),
    .y(P_0_4)
  );
  AndGate uut40 (
    .a(A[0]),
    .b(B[8]),
    .y(P_8_0)
  );
  AndGate uut41 (
    .a(A[1]),
    .b(B[8]),
    .y(P_8_1)
  );
  AndGate uut42 (
    .a(A[2]),
    .b(B[8]),
    .y(P_8_2)
  );
  AndGate uut43 (
    .a(A[3]),
    .b(B[8]),
    .y(P_8_3)
  );
  AndGate uut44 (
    .a(A[4]),
    .b(B[8]),
    .y(P_8_4)
  );
  AndGate uut45 (
    .a(A[0]),
    .b(B[9]),
    .y(P_9_0)
  );
  AndGate uut46 (
    .a(A[1]),
    .b(B[9]),
    .y(P_9_1)
  );
  AndGate uut47 (
    .a(A[2]),
    .b(B[9]),
    .y(P_9_2)
  );
  AndGate uut48 (
    .a(A[3]),
    .b(B[9]),
    .y(P_9_3)
  );
  AndGate uut49 (
    .a(A[4]),
    .b(B[9]),
    .y(P_9_4)
  );
  AndGate uut5 (
    .a(A[0]),
    .b(B[1]),
    .y(P_1_0)
  );
  AndGate uut50 (
    .a(A[0]),
    .b(B[10]),
    .y(P_10_0)
  );
  AndGate uut51 (
    .a(A[1]),
    .b(B[10]),
    .y(P_10_1)
  );
  AndGate uut52 (
    .a(A[2]),
    .b(B[10]),
    .y(P_10_2)
  );
  AndGate uut53 (
    .a(A[3]),
    .b(B[10]),
    .y(P_10_3)
  );
  AndGate uut54 (
    .a(A[4]),
    .b(B[10]),
    .y(P_10_4)
  );
  AndGate uut55 (
    .a(A[0]),
    .b(B[11]),
    .y(P_11_0)
  );
  AndGate uut56 (
    .a(A[1]),
    .b(B[11]),
    .y(P_11_1)
  );
  AndGate uut57 (
    .a(A[2]),
    .b(B[11]),
    .y(P_11_2)
  );
  AndGate uut58 (
    .a(A[3]),
    .b(B[11]),
    .y(P_11_3)
  );
  AndGate uut59 (
    .a(A[4]),
    .b(B[11]),
    .y(P_11_4)
  );
  AndGate uut6 (
    .a(A[1]),
    .b(B[1]),
    .y(P_1_1)
  );
  AndGate uut60 (
    .a(A[0]),
    .b(B[12]),
    .y(P_12_0)
  );
  AndGate uut61 (
    .a(A[1]),
    .b(B[12]),
    .y(P_12_1)
  );
  AndGate uut62 (
    .a(A[2]),
    .b(B[12]),
    .y(P_12_2)
  );
  AndGate uut63 (
    .a(A[3]),
    .b(B[12]),
    .y(P_12_3)
  );
  AndGate uut64 (
    .a(A[4]),
    .b(B[12]),
    .y(P_12_4)
  );
  AndGate uut65 (
    .a(A[0]),
    .b(B[13]),
    .y(P_13_0)
  );
  AndGate uut66 (
    .a(A[1]),
    .b(B[13]),
    .y(P_13_1)
  );
  AndGate uut67 (
    .a(A[2]),
    .b(B[13]),
    .y(P_13_2)
  );
  AndGate uut68 (
    .a(A[3]),
    .b(B[13]),
    .y(P_13_3)
  );
  AndGate uut69 (
    .a(A[4]),
    .b(B[13]),
    .y(P_13_4)
  );
  AndGate uut7 (
    .a(A[2]),
    .b(B[1]),
    .y(P_1_2)
  );
  AndGate uut70 (
    .a(A[0]),
    .b(B[14]),
    .y(P_14_0)
  );
  AndGate uut71 (
    .a(A[1]),
    .b(B[14]),
    .y(P_14_1)
  );
  AndGate uut72 (
    .a(A[2]),
    .b(B[14]),
    .y(P_14_2)
  );
  AndGate uut73 (
    .a(A[3]),
    .b(B[14]),
    .y(P_14_3)
  );
  AndGate uut74 (
    .a(A[4]),
    .b(B[14]),
    .y(P_14_4)
  );
  AndGate uut75 (
    .a(A[0]),
    .b(B[15]),
    .y(P_15_0)
  );
  AndGate uut76 (
    .a(A[1]),
    .b(B[15]),
    .y(P_15_1)
  );
  AndGate uut77 (
    .a(A[2]),
    .b(B[15]),
    .y(P_15_2)
  );
  AndGate uut78 (
    .a(A[3]),
    .b(B[15]),
    .y(P_15_3)
  );
  AndGate uut79 (
    .a(A[4]),
    .b(B[15]),
    .y(P_15_4)
  );
  AndGate uut8 (
    .a(A[3]),
    .b(B[1]),
    .y(P_1_3)
  );
  HalfAdder uut80 (
    .a(P_0_4),
    .b(P_1_3),
    .cout(c0),
    .sum(s0)
  );
  FullAdder uut81 (
    .a(P_1_4),
    .b(P_2_3),
    .cin(P_3_2),
    .cout(c1),
    .sum(s1)
  );
  FullAdder uut82 (
    .a(P_2_4),
    .b(P_3_3),
    .cin(P_4_2),
    .cout(c2),
    .sum(s2)
  );
  FullAdder uut83 (
    .a(P_3_4),
    .b(P_4_3),
    .cin(P_5_2),
    .cout(c3),
    .sum(s3)
  );
  FullAdder uut84 (
    .a(P_4_4),
    .b(P_5_3),
    .cin(P_6_2),
    .cout(c4),
    .sum(s4)
  );
  FullAdder uut85 (
    .a(P_5_4),
    .b(P_6_3),
    .cin(P_7_2),
    .cout(c5),
    .sum(s5)
  );
  FullAdder uut86 (
    .a(P_6_4),
    .b(P_7_3),
    .cin(P_8_2),
    .cout(c6),
    .sum(s6)
  );
  FullAdder uut87 (
    .a(P_7_4),
    .b(P_8_3),
    .cin(P_9_2),
    .cout(c7),
    .sum(s7)
  );
  FullAdder uut88 (
    .a(P_8_4),
    .b(P_9_3),
    .cin(P_10_2),
    .cout(c8),
    .sum(s8)
  );
  FullAdder uut89 (
    .a(P_9_4),
    .b(P_10_3),
    .cin(P_11_2),
    .cout(c9),
    .sum(s9)
  );
  AndGate uut9 (
    .a(A[4]),
    .b(B[1]),
    .y(P_1_4)
  );
  FullAdder uut90 (
    .a(P_10_4),
    .b(P_11_3),
    .cin(P_12_2),
    .cout(c10),
    .sum(s10)
  );
  FullAdder uut91 (
    .a(P_11_4),
    .b(P_12_3),
    .cin(P_13_2),
    .cout(c11),
    .sum(s11)
  );
  HalfAdder uut92 (
    .a(P_12_4),
    .b(P_13_3),
    .cout(c12),
    .sum(s12)
  );
  HalfAdder uut93 (
    .a(P_0_3),
    .b(P_1_2),
    .cout(c13),
    .sum(s13)
  );
  FullAdder uut94 (
    .a(P_2_2),
    .b(P_3_1),
    .cin(P_4_0),
    .cout(c14),
    .sum(s14)
  );
  FullAdder uut95 (
    .a(P_4_1),
    .b(P_5_0),
    .cin(c0),
    .cout(c15),
    .sum(s15)
  );
  FullAdder uut96 (
    .a(P_5_1),
    .b(P_6_0),
    .cin(c1),
    .cout(c16),
    .sum(s16)
  );
  FullAdder uut97 (
    .a(P_6_1),
    .b(P_7_0),
    .cin(c2),
    .cout(c17),
    .sum(s17)
  );
  FullAdder uut98 (
    .a(P_7_1),
    .b(P_8_0),
    .cin(c3),
    .cout(c18),
    .sum(s18)
  );
  FullAdder uut99 (
    .a(P_8_1),
    .b(P_9_0),
    .cin(c4),
    .cout(c19),
    .sum(s19)
  );
  assign Product[0] = P_0_0;
endmodule

module XorGate(A, B, Y);
  input A;
  wire A;
  input B;
  wire B;
  output Y;
  wire Y;
  XOR2xp5_ASAP7_75t_R _0_ (
    .A(B),
    .B(A),
    .Y(Y)
  );
endmodule

module unsignedBrentKungAdder19bit(A, B, Sum);
  input [18:0] A;
  wire [18:0] A;
  input [18:0] B;
  wire [18:0] B;
  wire G_0_0;
  wire G_0_1;
  wire G_0_10;
  wire G_0_11;
  wire G_0_12;
  wire G_0_13;
  wire G_0_14;
  wire G_0_15;
  wire G_0_16;
  wire G_0_17;
  wire G_0_18;
  wire G_0_2;
  wire G_0_3;
  wire G_0_4;
  wire G_0_5;
  wire G_0_6;
  wire G_0_7;
  wire G_0_8;
  wire G_0_9;
  wire G_1_1;
  wire G_1_11;
  wire G_1_13;
  wire G_1_15;
  wire G_1_17;
  wire G_1_3;
  wire G_1_5;
  wire G_1_7;
  wire G_1_9;
  wire G_2_11;
  wire G_2_15;
  wire G_2_3;
  wire G_2_7;
  wire G_3_15;
  wire G_3_7;
  wire G_4_15;
  wire G_7_11;
  wire G_8_13;
  wire G_8_17;
  wire G_8_5;
  wire G_8_9;
  wire G_9_10;
  wire G_9_12;
  wire G_9_14;
  wire G_9_16;
  wire G_9_18;
  wire G_9_2;
  wire G_9_4;
  wire G_9_6;
  wire G_9_8;
  wire P_0_0;
  wire P_0_1;
  wire P_0_10;
  wire P_0_11;
  wire P_0_12;
  wire P_0_13;
  wire P_0_14;
  wire P_0_15;
  wire P_0_16;
  wire P_0_17;
  wire P_0_18;
  wire P_0_2;
  wire P_0_3;
  wire P_0_4;
  wire P_0_5;
  wire P_0_6;
  wire P_0_7;
  wire P_0_8;
  wire P_0_9;
  wire P_1_1;
  wire P_1_11;
  wire P_1_13;
  wire P_1_15;
  wire P_1_17;
  wire P_1_3;
  wire P_1_5;
  wire P_1_7;
  wire P_1_9;
  wire P_2_11;
  wire P_2_15;
  wire P_2_3;
  wire P_2_7;
  wire P_3_15;
  wire P_3_7;
  wire P_4_15;
  wire P_7_11;
  wire P_8_13;
  wire P_8_17;
  wire P_8_5;
  wire P_8_9;
  wire P_9_10;
  wire P_9_12;
  wire P_9_14;
  wire P_9_16;
  wire P_9_18;
  wire P_9_2;
  wire P_9_4;
  wire P_9_6;
  wire P_9_8;
  output [19:0] Sum;
  wire [19:0] Sum;
  BitwisePG uut0 (
    .A(A[0]),
    .B(B[0]),
    .G(G_0_0),
    .P(P_0_0)
  );
  BitwisePG uut1 (
    .A(A[1]),
    .B(B[1]),
    .G(G_0_1),
    .P(P_0_1)
  );
  BitwisePG uut10 (
    .A(A[10]),
    .B(B[10]),
    .G(G_0_10),
    .P(P_0_10)
  );
  BitwisePG uut11 (
    .A(A[11]),
    .B(B[11]),
    .G(G_0_11),
    .P(P_0_11)
  );
  BitwisePG uut12 (
    .A(A[12]),
    .B(B[12]),
    .G(G_0_12),
    .P(P_0_12)
  );
  BitwisePG uut13 (
    .A(A[13]),
    .B(B[13]),
    .G(G_0_13),
    .P(P_0_13)
  );
  BitwisePG uut14 (
    .A(A[14]),
    .B(B[14]),
    .G(G_0_14),
    .P(P_0_14)
  );
  BitwisePG uut15 (
    .A(A[15]),
    .B(B[15]),
    .G(G_0_15),
    .P(P_0_15)
  );
  BitwisePG uut16 (
    .A(A[16]),
    .B(B[16]),
    .G(G_0_16),
    .P(P_0_16)
  );
  BitwisePG uut17 (
    .A(A[17]),
    .B(B[17]),
    .G(G_0_17),
    .P(P_0_17)
  );
  BitwisePG uut18 (
    .A(A[18]),
    .B(B[18]),
    .G(G_0_18),
    .P(P_0_18)
  );
  GrayCell uut19 (
    .Cin(G_0_0),
    .G(G_1_1),
    .Gi(G_0_1),
    .P(P_1_1),
    .Pi(P_0_1)
  );
  BitwisePG uut2 (
    .A(A[2]),
    .B(B[2]),
    .G(G_0_2),
    .P(P_0_2)
  );
  BlackCell uut20 (
    .Cin(G_0_2),
    .G(G_1_3),
    .Gi(G_0_3),
    .P(P_1_3),
    .Pi(P_0_3),
    .Pj(P_0_2)
  );
  BlackCell uut21 (
    .Cin(G_0_4),
    .G(G_1_5),
    .Gi(G_0_5),
    .P(P_1_5),
    .Pi(P_0_5),
    .Pj(P_0_4)
  );
  BlackCell uut22 (
    .Cin(G_0_6),
    .G(G_1_7),
    .Gi(G_0_7),
    .P(P_1_7),
    .Pi(P_0_7),
    .Pj(P_0_6)
  );
  BlackCell uut23 (
    .Cin(G_0_8),
    .G(G_1_9),
    .Gi(G_0_9),
    .P(P_1_9),
    .Pi(P_0_9),
    .Pj(P_0_8)
  );
  BlackCell uut24 (
    .Cin(G_0_10),
    .G(G_1_11),
    .Gi(G_0_11),
    .P(P_1_11),
    .Pi(P_0_11),
    .Pj(P_0_10)
  );
  BlackCell uut25 (
    .Cin(G_0_12),
    .G(G_1_13),
    .Gi(G_0_13),
    .P(P_1_13),
    .Pi(P_0_13),
    .Pj(P_0_12)
  );
  BlackCell uut26 (
    .Cin(G_0_14),
    .G(G_1_15),
    .Gi(G_0_15),
    .P(P_1_15),
    .Pi(P_0_15),
    .Pj(P_0_14)
  );
  BlackCell uut27 (
    .Cin(G_0_16),
    .G(G_1_17),
    .Gi(G_0_17),
    .P(P_1_17),
    .Pi(P_0_17),
    .Pj(P_0_16)
  );
  GrayCell uut28 (
    .Cin(G_1_1),
    .G(G_2_3),
    .Gi(G_1_3),
    .P(P_2_3),
    .Pi(P_1_3)
  );
  BlackCell uut29 (
    .Cin(G_1_5),
    .G(G_2_7),
    .Gi(G_1_7),
    .P(P_2_7),
    .Pi(P_1_7),
    .Pj(P_1_5)
  );
  BitwisePG uut3 (
    .A(A[3]),
    .B(B[3]),
    .G(G_0_3),
    .P(P_0_3)
  );
  BlackCell uut30 (
    .Cin(G_1_9),
    .G(G_2_11),
    .Gi(G_1_11),
    .P(P_2_11),
    .Pi(P_1_11),
    .Pj(P_1_9)
  );
  BlackCell uut31 (
    .Cin(G_1_13),
    .G(G_2_15),
    .Gi(G_1_15),
    .P(P_2_15),
    .Pi(P_1_15),
    .Pj(P_1_13)
  );
  GrayCell uut32 (
    .Cin(G_2_3),
    .G(G_3_7),
    .Gi(G_2_7),
    .P(P_3_7),
    .Pi(P_2_7)
  );
  BlackCell uut33 (
    .Cin(G_2_11),
    .G(G_3_15),
    .Gi(G_2_15),
    .P(P_3_15),
    .Pi(P_2_15),
    .Pj(P_2_11)
  );
  GrayCell uut34 (
    .Cin(G_3_7),
    .G(G_4_15),
    .Gi(G_3_15),
    .P(P_4_15),
    .Pi(P_3_15)
  );
  GrayCell uut35 (
    .Cin(G_3_7),
    .G(G_7_11),
    .Gi(G_2_11),
    .P(P_7_11),
    .Pi(P_2_11)
  );
  GrayCell uut36 (
    .Cin(G_2_3),
    .G(G_8_5),
    .Gi(G_1_5),
    .P(P_8_5),
    .Pi(P_1_5)
  );
  GrayCell uut37 (
    .Cin(G_3_7),
    .G(G_8_9),
    .Gi(G_1_9),
    .P(P_8_9),
    .Pi(P_1_9)
  );
  GrayCell uut38 (
    .Cin(G_7_11),
    .G(G_8_13),
    .Gi(G_1_13),
    .P(P_8_13),
    .Pi(P_1_13)
  );
  GrayCell uut39 (
    .Cin(G_4_15),
    .G(G_8_17),
    .Gi(G_1_17),
    .P(P_8_17),
    .Pi(P_1_17)
  );
  BitwisePG uut4 (
    .A(A[4]),
    .B(B[4]),
    .G(G_0_4),
    .P(P_0_4)
  );
  GrayCell uut40 (
    .Cin(G_1_1),
    .G(G_9_2),
    .Gi(G_0_2),
    .P(P_9_2),
    .Pi(P_0_2)
  );
  GrayCell uut41 (
    .Cin(G_2_3),
    .G(G_9_4),
    .Gi(G_0_4),
    .P(P_9_4),
    .Pi(P_0_4)
  );
  GrayCell uut42 (
    .Cin(G_8_5),
    .G(G_9_6),
    .Gi(G_0_6),
    .P(P_9_6),
    .Pi(P_0_6)
  );
  GrayCell uut43 (
    .Cin(G_3_7),
    .G(G_9_8),
    .Gi(G_0_8),
    .P(P_9_8),
    .Pi(P_0_8)
  );
  GrayCell uut44 (
    .Cin(G_8_9),
    .G(G_9_10),
    .Gi(G_0_10),
    .P(P_9_10),
    .Pi(P_0_10)
  );
  GrayCell uut45 (
    .Cin(G_7_11),
    .G(G_9_12),
    .Gi(G_0_12),
    .P(P_9_12),
    .Pi(P_0_12)
  );
  GrayCell uut46 (
    .Cin(G_8_13),
    .G(G_9_14),
    .Gi(G_0_14),
    .P(P_9_14),
    .Pi(P_0_14)
  );
  GrayCell uut47 (
    .Cin(G_4_15),
    .G(G_9_16),
    .Gi(G_0_16),
    .P(P_9_16),
    .Pi(P_0_16)
  );
  GrayCell uut48 (
    .Cin(G_8_17),
    .G(G_9_18),
    .Gi(G_0_18),
    .P(P_9_18),
    .Pi(P_0_18)
  );
  XorGate uut49 (
    .A(P_0_1),
    .B(G_0_0),
    .Y(Sum[1])
  );
  BitwisePG uut5 (
    .A(A[5]),
    .B(B[5]),
    .G(G_0_5),
    .P(P_0_5)
  );
  XorGate uut50 (
    .A(P_0_2),
    .B(G_1_1),
    .Y(Sum[2])
  );
  XorGate uut51 (
    .A(P_0_3),
    .B(G_9_2),
    .Y(Sum[3])
  );
  XorGate uut52 (
    .A(P_0_4),
    .B(G_2_3),
    .Y(Sum[4])
  );
  XorGate uut53 (
    .A(P_0_5),
    .B(G_9_4),
    .Y(Sum[5])
  );
  XorGate uut54 (
    .A(P_0_6),
    .B(G_8_5),
    .Y(Sum[6])
  );
  XorGate uut55 (
    .A(P_0_7),
    .B(G_9_6),
    .Y(Sum[7])
  );
  XorGate uut56 (
    .A(P_0_8),
    .B(G_3_7),
    .Y(Sum[8])
  );
  XorGate uut57 (
    .A(P_0_9),
    .B(G_9_8),
    .Y(Sum[9])
  );
  XorGate uut58 (
    .A(P_0_10),
    .B(G_8_9),
    .Y(Sum[10])
  );
  XorGate uut59 (
    .A(P_0_11),
    .B(G_9_10),
    .Y(Sum[11])
  );
  BitwisePG uut6 (
    .A(A[6]),
    .B(B[6]),
    .G(G_0_6),
    .P(P_0_6)
  );
  XorGate uut60 (
    .A(P_0_12),
    .B(G_7_11),
    .Y(Sum[12])
  );
  XorGate uut61 (
    .A(P_0_13),
    .B(G_9_12),
    .Y(Sum[13])
  );
  XorGate uut62 (
    .A(P_0_14),
    .B(G_8_13),
    .Y(Sum[14])
  );
  XorGate uut63 (
    .A(P_0_15),
    .B(G_9_14),
    .Y(Sum[15])
  );
  XorGate uut64 (
    .A(P_0_16),
    .B(G_4_15),
    .Y(Sum[16])
  );
  XorGate uut65 (
    .A(P_0_17),
    .B(G_9_16),
    .Y(Sum[17])
  );
  XorGate uut66 (
    .A(P_0_18),
    .B(G_8_17),
    .Y(Sum[18])
  );
  BitwisePG uut7 (
    .A(A[7]),
    .B(B[7]),
    .G(G_0_7),
    .P(P_0_7)
  );
  BitwisePG uut8 (
    .A(A[8]),
    .B(B[8]),
    .G(G_0_8),
    .P(P_0_8)
  );
  BitwisePG uut9 (
    .A(A[9]),
    .B(B[9]),
    .G(G_0_9),
    .P(P_0_9)
  );
  assign { Sum[19], Sum[0] } = { G_9_18, P_0_0 };
endmodule
