/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, g++ 12.2.0-14 -fPIC -O3) */

module NR_1_4(IN1, IN2, Out);
  input IN1;
  wire IN1;
  input [3:0] IN2;
  wire [3:0] IN2;
  output [3:0] Out;
  wire [3:0] Out;
  AND _0_ (
    .A(IN1),
    .B(IN2[0]),
    .Y(Out[0])
  );
  AND _1_ (
    .A(IN1),
    .B(IN2[1]),
    .Y(Out[1])
  );
  AND _2_ (
    .A(IN1),
    .B(IN2[2]),
    .Y(Out[2])
  );
  AND _3_ (
    .A(IN1),
    .B(IN2[3]),
    .Y(Out[3])
  );
endmodule
