/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, g++ 12.2.0-14 -fPIC -O3) */

module NR_12_1(IN1, IN2, Out);
  input [11:0] IN1;
  wire [11:0] IN1;
  input IN2;
  wire IN2;
  output [11:0] Out;
  wire [11:0] Out;
  AND _00_ (
    .A(IN2),
    .B(IN1[0]),
    .Y(Out[0])
  );
  AND _01_ (
    .A(IN2),
    .B(IN1[10]),
    .Y(Out[10])
  );
  AND _02_ (
    .A(IN2),
    .B(IN1[11]),
    .Y(Out[11])
  );
  AND _03_ (
    .A(IN2),
    .B(IN1[1]),
    .Y(Out[1])
  );
  AND _04_ (
    .A(IN2),
    .B(IN1[2]),
    .Y(Out[2])
  );
  AND _05_ (
    .A(IN2),
    .B(IN1[3]),
    .Y(Out[3])
  );
  AND _06_ (
    .A(IN2),
    .B(IN1[4]),
    .Y(Out[4])
  );
  AND _07_ (
    .A(IN2),
    .B(IN1[5]),
    .Y(Out[5])
  );
  AND _08_ (
    .A(IN2),
    .B(IN1[6]),
    .Y(Out[6])
  );
  AND _09_ (
    .A(IN2),
    .B(IN1[7]),
    .Y(Out[7])
  );
  AND _10_ (
    .A(IN2),
    .B(IN1[8]),
    .Y(Out[8])
  );
  AND _11_ (
    .A(IN2),
    .B(IN1[9]),
    .Y(Out[9])
  );
endmodule
