/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, g++ 12.2.0-14 -fPIC -O3) */

module NR_1_11(IN1, IN2, Out);
  input IN1;
  wire IN1;
  input [10:0] IN2;
  wire [10:0] IN2;
  output [10:0] Out;
  wire [10:0] Out;
  AND _00_ (
    .A(IN1),
    .B(IN2[0]),
    .Y(Out[0])
  );
  AND _01_ (
    .A(IN1),
    .B(IN2[10]),
    .Y(Out[10])
  );
  AND _02_ (
    .A(IN1),
    .B(IN2[1]),
    .Y(Out[1])
  );
  AND _03_ (
    .A(IN1),
    .B(IN2[2]),
    .Y(Out[2])
  );
  AND _04_ (
    .A(IN1),
    .B(IN2[3]),
    .Y(Out[3])
  );
  AND _05_ (
    .A(IN1),
    .B(IN2[4]),
    .Y(Out[4])
  );
  AND _06_ (
    .A(IN1),
    .B(IN2[5]),
    .Y(Out[5])
  );
  AND _07_ (
    .A(IN1),
    .B(IN2[6]),
    .Y(Out[6])
  );
  AND _08_ (
    .A(IN1),
    .B(IN2[7]),
    .Y(Out[7])
  );
  AND _09_ (
    .A(IN1),
    .B(IN2[8]),
    .Y(Out[8])
  );
  AND _10_ (
    .A(IN1),
    .B(IN2[9]),
    .Y(Out[9])
  );
endmodule
