/* Generated by Yosys 0.45+139 (git sha1 8e1e2b9a3, g++ 12.2.0-14 -fPIC -O3) */

module NR_7_1(IN1, IN2, Out);
  input [6:0] IN1;
  wire [6:0] IN1;
  input IN2;
  wire IN2;
  output [6:0] Out;
  wire [6:0] Out;
  AND _0_ (
    .A(IN2),
    .B(IN1[2]),
    .Y(Out[2])
  );
  AND _1_ (
    .A(IN2),
    .B(IN1[3]),
    .Y(Out[3])
  );
  AND _2_ (
    .A(IN2),
    .B(IN1[4]),
    .Y(Out[4])
  );
  AND _3_ (
    .A(IN2),
    .B(IN1[5]),
    .Y(Out[5])
  );
  AND _4_ (
    .A(IN2),
    .B(IN1[6]),
    .Y(Out[6])
  );
  AND _5_ (
    .A(IN2),
    .B(IN1[0]),
    .Y(Out[0])
  );
  AND _6_ (
    .A(IN2),
    .B(IN1[1]),
    .Y(Out[1])
  );
endmodule
